{{- if .Values.ingress.enabled }}
<<<<<<< HEAD
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-autoscaling
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    {{- range .Values.ingress.autoscaling.stacks }}
=======
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-monitoring
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    {{- range .Values.ingress.monitoring.stacks }}
>>>>>>> 50dced335248a395d93e0ace9ab7a818ffafb886
    - {{ .host | quote }}
    {{- end }}
  gateways:
    - {{ .Values.ingress.gateway | quote }}
  http:
<<<<<<< HEAD
    {{- range .Values.ingress.autoscaling.stacks }}
=======
    {{- range .Values.ingress.monitoring.stacks }}
>>>>>>> 50dced335248a395d93e0ace9ab7a818ffafb886
    - name: {{ .name | quote }}
      match:
        - headers:
            host:
              exact: {{ .host | quote }}
      route:
        - destination:
            host: {{ printf "%s.%s.svc.cluster.local" .serviceName $.Release.Namespace | quote }}
            port:
              number: {{ .port }}
    {{- end }}
{{- end }}