{{- if .Values.externalSecrets.enabled }}
{{- range $name, $secret := .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.target.name }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "argocd.secretStoreName" . }}
    kind: SecretStore
  target:
    name: {{ $secret.target.name }}
    creationPolicy: Owner

  {{- if $secret.template }}
  template:
{{ toYaml $secret.template | indent 4 }}
  {{- end }}

  data:
{{ toYaml $secret.data | indent 4 }}

{{- end }}
{{- end }}

