apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-gitops-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-backend
    kind: ClusterSecretStore
  target:
    name: petclinic-gitops-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        url: "git@github.com:silasfrancis/petclinic-gitops.git"
        sshPrivateKey: "{{ .sshPrivateKey }}"
        insecure: "false"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: petclinic/argocd/
        property: deploy-key