{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "argocd.secretStoreName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd.labels" . | nindent 4}}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "argocd.serviceAccountName" . }}
{{- end }}