environment = "dev"
aws_region  = "us-east-2"
app         = "petclinic"
owner       = "silasfrancis"
repo        = "https://github.com/silasfrancis/eks-platform-petclinic"
language    = "java"
framework   = "spring-boot"