apiVersion: v2
name: compute
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: karpenter
    version: "1.0.0"
    repository: oci://public.ecr.aws/karpenter