namespace: istio-system

selectorLabels:
  app: istio-ingressgateway
  istio: ingressgateway

serviceAccount:
  name: istio-ingressgateway
  enabled: true

role:
  name: istio-ingressgateway-sds
  enabled: true
  rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

roleBinding:
  name: istio-ingressgateway-sds
  enabled: true

containers:
  name: istio-ingressgateway
  image: docker.io/istio/proxyv2:1.29.1
  command:
    - pilot-agent
    - proxy
    - router
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
  env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

deployment:
  enabled: true
  name: istio-ingressgateway
  annotations:
    inject.istio.io/templates: gateway
  labels:
    sidecar.istio.io/inject: "true"

horizontalPodAutoscaler:
  enabled: true
  name: istio-ingressgateway
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

podDisruptionBudget:
  enabled: true
  name: istio-ingressgateway
  minAvailable: 1

loadbalancer:
  enabled: true
  name: istio-ingressgateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "petclinic-dev-istio-nlb"
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-021845a2ee47579d9,subnet-0d277d84a61c8d17e"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0cad46885e6fd10d6"
  istioTargetPorts:
    http: 8080
    https: 8080

gateway:
  name: petclinic-gateway
  enabled: true
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "petclinic.lefrancis.org"
