clusterIssuer:
  enabled: true
  email: "silas@lefrancis.org"
  existingSecret:
    name: "cloudflare-dns-token"
    key: "cloudflare-api-token"

falco:
  nodeSelector:
    falco-enabled: "true"

externalSecret:
  enabled: true
  targetSecret: "platform-security-secrets"
  data:
    - secretKey: slack-webhook-url
      remoteRef:
        key: prod/platform-monitoring
        property: slack-webhook-url

serviceAccount:
  create: true
  name: "platform-security-sa"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-platform-security-secrets-irsa"
