apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customers-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/silasfrancis/petclinic-gitops
    targetRevision: main
    path: k8s/microservice  
    helm:
      valueFiles:
        - values.yaml                
        - values/env/dev/customers-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true