cluster:
  name: "dev-petclinic-cluster"
  env: "dev"
  app: "petclinic"
  nodeRoleName: "dev-petclinic-node-role"
  kmsKeyArn: ""

karpenter:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ""
  settings:
    clusterName: "dev-petclinic"
    interruptionQueue: ""

nodePools:
  on-demand:
    limits:
      cpu: "4"
      memory: 8Gi
      nodes: 2
    disruption:
      consolidateAfter: 5m

  spot:
    limits:
      cpu: "4"
      memory: 8Gi
      nodes: 2