apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-app-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{}}
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "{{}}"
      minAllowed:
        cpu: 200m
        memory: 512Mi
      maxAllowed:
        cpu: 700m
        memory: 1Gi
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsAndLimits