{{- if eq .Values.controller.type "rollout" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "microservice.rolloutName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  revisionHistoryLimit: {{ .Values.workload.revisionHistoryLimit | default 5 }}
  minReadySeconds: {{ .Values.workload.minReadySeconds | default 30 }}
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  strategy:
    {{- include "microservice.strategy" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "microservice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSpec }}
      {{- if hasKey . "hostPID" }}
      hostPID: {{ .hostPID }}
      {{- end }}
      {{- if hasKey . "hostIPC" }}
      hostIPC: {{ .hostIPC }}
      {{- end }}
      {{- if hasKey . "hostNetwork" }}
      hostNetwork: {{ .hostNetwork }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "microservice.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- $nodeSelector := include "microservice.nodeSelector" . }}
      {{- if $nodeSelector }}
      nodeSelector:
        {{- $nodeSelector | nindent 8 }}
      {{- end }}
      {{- $tolerations := include "microservice.tolerations" . }}
      {{- if $tolerations }}
      tolerations:
        {{- $tolerations | nindent 8 }}
      {{- end }}
      {{- $affinity := include "microservice.affinity" . }}
      {{- if $affinity }}
      affinity:
        {{- $affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ include "microservice.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.containerPort | default 8080 }}
              protocol: TCP
          env:
            {{- include "microservice.commonEnv" . | nindent 12 }}
          {{- if and .Values.externalSecret .Values.externalSecret.enabled }}
          envFrom:
            - secretRef:
                name: {{ include "microservice.externalSecretName" . }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- include "microservice.probes" . | nindent 10 }} 
{{- end }}