{{- if .Values.destinationRule.enabled }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ include "microservice.drName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  host: {{ include "microservice.fqdn" . }}
  subsets:
    - name: stable
      labels:
        app: {{ .Values.appName }}
    - name: canary
      labels:
        app: {{ .Values.appName }}
{{- end }}