{{- if eq .Values.controller.type "rollout" }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.appName }}-dr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  host: {{ include "microservice.serviceName" . }}
  subsets:
    - name: stable
      labels:
        app: {{ .Values.appName }}
    - name: canary
      labels:
        app: {{ .Values.appName }}
{{- end }}