{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "microservice.externalSecretName" . }}
  namespace: {{ .Release.Namespace }}
  {{- $annotations := include "microservice.workloadAnnotations" . | fromYaml }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval:  {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ include "microservice.secretStoreName" . }}
    kind: SecretStore
  target:
    name: {{ include "microservice.secretName" . }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef: 
      key: {{ .remoteRef.key }}
      property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}