{{- if and .Values.podDisruptionBudget.enabled (ne .Values.controller.type "job") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "microservice.pdbName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
{{- end }}