{{- if and .Values.scaleObject.enabled (ne .Values.controller.type "job") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "microservice.scaleObjectName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.scaleObject.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    {{- if eq .Values.controller.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "microservice.rolloutName" . }}
    {{- else if eq .Values.controller.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "microservice.deploymentName" . }}
    {{- end }}
  minReplicaCount: {{ .Values.scaleObject.minReplicas }}
  maxReplicaCount: {{ .Values.scaleObject.maxReplicas }}
  idleReplicaCount: {{ .Values.scaleObject.idleReplicaCount }}
  pollingInterval: {{ .Values.scaleObject.pollingInterval }}
  cooldownPeriod: {{ .Values.scaleObject.cooldownPeriod }}
  {{- if .Values.scaleObject.fallback }}
  fallback:
    {{- toYaml .Values.scaleObject.fallback | nindent 4 }}
  {{- end }}
  triggers:
    {{- include "microservice.scaleObjectBaseTriggers" . | nindent 4 }}
{{- end }}