{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "microservice.secretStoreName" . }}
  namespace: {{ .Release.Namespace }}
  {{- $annotations := include "microservice.workloadAnnotations" . | fromYaml }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "microservice.serviceAccountName" . }}
{{- end }}