{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAccount.annotations }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
{{- end }}