{{- if .Values.serviceMonitor.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "microservice.serviceMonitorName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.standardLabels" . | nindent 4 }}
    {{- toYaml .Values.serviceMonitor.selectorLabels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.serviceMonitor.portName }}
      path: {{ .Values.serviceMonitor.endpoint }}
      interval: 15s
      honorLabels: true
{{- end }}