{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "microservice.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  hosts:
    {{- if .Values.virtualService.host }}
    - {{ .Values.virtualService.host }} 
    {{- end }}
    - {{ include "microservice.fqdn" . }}
  {{- if .Values.virtualService.host }}
  gateways:
    - {{ .Values.virtualService.gateway }}
    - mesh
  {{- else }}
  gateways:
    - mesh
  {{- end }}
  http:
    {{- if .Values.virtualService.routes }}
    {{- toYaml .Values.virtualService.routes | nindent 4 }}
    {{- end }}
    {{- if eq .Values.controller.type "rollout" }}
    - name: primary
      route:
        - destination:
            host: {{ include "microservice.fqdn" . }}
            subset: stable
            port:
              number: {{ .Values.service.port }}
          weight: 100
        - destination:
            host: {{ include "microservice.fqdn" . }}
            subset: canary
            port:
              number: {{ .Values.service.port }}
          weight: 0
    {{- else }}
    - name: primary
      route:
        - destination:
            host: {{ include "microservice.fqdn" . }}
            port:
              number: {{ .Values.service.port }}
    {{- end }}
{{- end }}