{{- if and .Values.vpa.enabled (ne .Values.controller.type "job") }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "microservice.vpaName" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  targetRef:
    {{- if eq .Values.controller.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "microservice.rolloutName" . }}
    {{- else if eq .Values.controller.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "microservice.deploymentName" . }}
    {{- end }}
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Values.appName }}
        minAllowed:
          cpu: {{ .Values.vpa.minAllowed.cpu | quote }}
          memory: {{ .Values.vpa.minAllowed.memory | quote }}
        maxAllowed:
          cpu: {{ .Values.vpa.maxAllowed.cpu | quote }}
          memory: {{ .Values.vpa.maxAllowed.memory | quote }}
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsAndLimits
{{- end }}