apiVersion: policies.kyverno.io/v1
kind: NamespacedImageValidatingPolicy
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      policies:policies.kyverno.io/NamespacedImageValidatingPolicy:petclinic/verify-image-provenance
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: platform-policies
    policy.kyverno.io/version: v1
  name: verify-image-provenance
  namespace: petclinic
spec:
  attestations:
    - intoto:
        type: cosign.sigstore.dev/attestation/vuln/v1
      name: vulnScan
  attestors:
    - cosign:
        ctlog:
          url: https://rekor.sigstore.dev
        keyless:
          identities:
            - issuer: https://token.actions.githubusercontent.com
              subject: >-
                https://github.com/silasfrancis/eks-platform-petclinic/.github/workflows/build-push.yaml@refs/heads/main
      name: attestor-0
    - cosign:
        ctlog:
          url: https://rekor.sigstore.dev
        keyless:
          identities:
            - issuer: https://token.actions.githubusercontent.com
              subject: >-
                https://github.com/silasfrancis/eks-platform-petclinic/.github/workflows/build-migrations.yaml@refs/heads/main
      name: attestor-1
  credentials:
    allowInsecureRegistry: false
    providers:
      - amazon
  evaluation:
    admission:
      enabled: true
    background:
      enabled: false
    mode: Kubernetes
  failurePolicy: Ignore
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
  matchImageReferences:
    - glob: 509194952955.dkr.ecr.us-east-2.amazonaws.com/petclinic/*
  validationActions:
    - Deny
  validationConfigurations:
    mutateDigest: true
    required: true
    verifyDigest: true
  validations:
    - expression: |-
        images.containers.map(image,
          verifyImageSignatures(image, [attestors['attestor-0']]) > 0 || verifyImageSignatures(image, [attestors['attestor-1']]) > 0
        ).all(e, e)
      message: Container Images must be signed by an authorized GitHub workflow
    - expression: |-
        !has(object.spec.initContainers) || images.initContainers.map(image,
          verifyImageSignatures(image, [attestors['attestor-0']]) > 0 || verifyImageSignatures(image, [attestors['attestor-1']]) > 0
        ).all(e, e)
      message: Init container image must be signed by an authorized GitHub workflow
    - expression: |-
        images.containers.map(image,
          verifyAttestationSignatures(image, attestations.vulnScan, [attestors['attestor-0']]) > 0 || verifyAttestationSignatures(image, attestations.vulnScan, [attestors['attestor-1']]) > 0
        ).all(e, e)
      message: >-
        Container Images must have a verified vulnerability scan attestation
        from an authorized GitHub workflow.
    - expression: |-
        !has(object.spec.initContainers) || images.initContainers.map(image,
          verifyAttestationSignatures(image, attestations.vulnScan, [attestors['attestor-0']]) > 0 || verifyAttestationSignatures(image, attestations.vulnScan, [attestors['attestor-1']]) > 0
        ).all(e, e)
      message: >-
        Init container image must have a verified vulnerability scan attestation
        from an authorized GitHub workflow.
  webhookConfiguration:
    timeoutSeconds: 3
