{
 "title": "SLO / Error Budget Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(istio_requests_total{destination_service_namespace=~\"$namespace\"},destination_service_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   { "name": "window", "query": "30d,7d,1d" }
  ]
 },
 "panels": [
  { "title": " Current SLO status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability per service",
   "type": "stat",
   "description": "Availability per service for specified window",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  1 - (\r\n    sum by (destination_service_name) (\r\n      sum_over_time(\r\n        istio_requests_total{\r\n          reporter=\"destination\",\r\n          destination_service_namespace=~\"$namespace\",\r\n          destination_service_name=~\"$service\",\r\n          response_code=~\"5.*\"\r\n        }[$window]\r\n      )\r\n    )\r\n    /\r\n    sum by (destination_service_name) (\r\n      sum_over_time(\r\n        istio_requests_total{\r\n          reporter=\"destination\",\r\n          destination_service_namespace=~\"$namespace\",\r\n          destination_service_name=~\"$service\"\r\n        }[$window]\r\n      )\r\n    )\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error budget remaining",
   "type": "stat",
   "description": "Error budget remaining",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  1 - (\r\n    sum by (destination_service_name) (\r\n      sum_over_time(\r\n        istio_requests_total{\r\n          reporter=\"destination\",\r\n          destination_service_namespace=~\"$namespace\",\r\n          destination_service_name=~\"$service\",\r\n          response_code=~\"5.*\"\r\n        }[$window]\r\n      )\r\n    )\r\n    /\r\n    (\r\n      sum by (destination_service_name) (\r\n        sum_over_time(\r\n          istio_requests_total{\r\n            reporter=\"destination\",\r\n            destination_service_namespace=~\"$namespace\",\r\n            destination_service_name=~\"$service\"\r\n          }[$window]\r\n        )\r\n      ) * 0.001\r\n    )\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 latency SLO compliance",
   "type": "stat",
   "description": "p99 latency SLO compliance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (\r\n  rate(istio_request_duration_milliseconds_bucket{\r\n    reporter=\"destination\",\r\n    destination_service_namespace=~\"$namespace\",\r\n    destination_service_name=~\"$service\",\r\n    le=\"200\"\r\n  }[$window])\r\n)\r\n/\r\nsum by (destination_service_name) (\r\n  rate(istio_request_duration_milliseconds_bucket{\r\n    reporter=\"destination\",\r\n    destination_service_namespace=~\"$namespace\",\r\n    destination_service_name=~\"$service\",\r\n    le=\"+Inf\"\r\n  }[$window]\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Burn rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Burn rate 1h vs 6 h",
   "type": "timeseries",
   "description": "Burn rate 1h vs 6 h",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(\r\n  sum by (destination_service_name) (\r\n    rate(istio_requests_total{\r\n      reporter=\"destination\",\r\n      destination_service_namespace=~\"$namespace\",\r\n      destination_service_name=~\"$service\",\r\n      response_code=~\"5.*\"\r\n    }[1h])\r\n  )\r\n  /\r\n  sum by (destination_service_name) (\r\n    rate(istio_requests_total{\r\n      reporter=\"destination\",\r\n      destination_service_namespace=~\"$namespace\",\r\n      destination_service_name=~\"$service\"\r\n    }[1h])\r\n  )\r\n) / 0.001",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  sum by (destination_service_name) (\r\n    rate(istio_requests_total{\r\n      reporter=\"destination\",\r\n      destination_service_namespace=~\"$namespace\",\r\n      destination_service_name=~\"$service\",\r\n      response_code=~\"5.*\"\r\n    }[6h])\r\n  )\r\n  /\r\n  sum by (destination_service_name) (\r\n    rate(istio_requests_total{\r\n      reporter=\"destination\",\r\n      destination_service_namespace=~\"$namespace\",\r\n      destination_service_name=~\"$service\"\r\n    }[6h])\r\n  )\r\n) / 0.001",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}