namespace: istio-system

selectorLabels:
  app: istio-ingressgateway
  istio: ingressgateway

serviceAccount:
  name: istio-ingressgateway
  enabled: true

role:
  name: istio-ingressgateway-sds
  enabled: true
  rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

roleBinding:
  name: istio-ingressgateway-sds
  enabled: true

containers:
  name: istio-ingressgateway
  image: auto
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

deployment:
  enabled: true
  name: istio-ingressgateway
  annotations:
    inject.istio.io/templates: gateway
  labels:
    sidecar.istio.io/inject: "true"

horizontalPodAutoscaler:
  enabled: true
  name: istio-ingressgateway
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

podDisruptionBudget:
  enabled: true
  name: istio-ingressgateway
  minAvailable: 1

loadbalancer:
  enabled: true
  name: istio-ingressgateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-021845a2ee47579d9,subnet-0d277d84a61c8d17e"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0cad46885e6fd10d6"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-2:509194952955:certificate/5c89628b-b98b-494a-8218-5526c953a098"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "petclinic-dev-silas-dev-alb-logs"
  istioTargetPorts:
    http: 8080
    https: 8080

gateway:
  name: petclinic-gateway
  enabled: true
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "petclinic.lefrancis.org"
