public-gateway:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: "petclinic-prod-nlb"
      service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0046e541e134bdf51,subnet-0e9b6a8bff1e567df"
      service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0c001586959484a14"
      external-dns.alpha.kubernetes.io/provider: "cloudflare"
      external-dns.alpha.kubernetes.io/hostname: "petclinic.lefrancis.org"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      external-dns.alpha.kubernetes.io/ttl: "120"

internal-gateway:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: "petclinic-prod-internal-nlb"
      service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-044992ee95201b5c1,subnet-0ecc34f4b08bff593"
      service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0dc41a3456b836fa6"
      external-dns.alpha.kubernetes.io/provider: "route53"
      external-dns.alpha.kubernetes.io/hostname: "grafana.internal.lefrancis.org,argocd.internal.lefrancis.org,prometheus.internal.lefrancis.org,loki.internal.lefrancis.org,goldilocks.internal.lefrancis.org,falcosidekick.internal.lefrancis.org"
      external-dns.alpha.kubernetes.io/ttl: "120"

customCertificates:
  public:
    secretName: "petclinic-public-tls"
    issuerRefName: "security-cluster-issuer"
    hosts:
      - "*.lefrancis.org"
  internal:
    secretName: "petclinic-internal-tls"
    issuerRefName: "security-cluster-issuer"
    hosts:
      - "*.internal.lefrancis.org"



external-dns-cloudflare:
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: cloudflare-api-token

  registry: txt
  txtOwnerId: "eks-cluster-01-cloudflare"
  txtPrefix: "cloudflare-"

external-dns-route53:
  provider:
    name: aws
  serviceAccount:
    create: true
    name: external-dns-route53
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-external-dns-route53-irsa"

  registry: txt
  txtOwnerId: "eks-cluster-01-route53"
  txtPrefix: "route53-"

secretStore:
  enabled: true
  name: ""

externalSecret:
  enabled: true
  name: ""
  refreshInterval: 1h
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: "prod/platform-dns"
        property: cloudflare-api-token

esoServiceAccount:
  name: "external-dns-cloudflare"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-external-dns-secrets-irsa"
