namespace: kube-system

serviceAccount:
  name: aws-load-balancer-controller
  enabled: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-petclinic-alb-controller"

clusterIssuer:
  enabled: true
  name: letsencrypt-cloudflare
  spec:
    acme:
      server: https://acme-v02.api.letsencrypt.org/directory
      email: silasfrancis07@gmail.com
      privateKeySecretRef:
        name: letsencrypt-cloudflare-account-key
      solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
