apiVersion: policies.kyverno.io/v1
kind: NamespacedValidatingPolicy
metadata:
  name: pod-security
  namespace: petclinic
spec:
  webhookConfiguration:
    timeoutSeconds: 15
  evaluation:
    admission:
      enabled: true
    background:
      enabled: false
    mode: Kubernetes
  validationActions: [Deny]
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE', 'UPDATE']
        resources: ['pods']

  variables:
    - name: appContainers
      expression: >-
        object.spec.containers.filter(c,
          !c.image.startsWith("docker.io/istio/") &&
          !c.image.startsWith("gcr.io/istio-release/")
        )

  validations:
    - message: 'Privileged containers are not allowed'
      expression: >-
        variables.appContainers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.privileged) ||
          c.securityContext.privileged == false
        )

    - message: 'Containers must run as non-root'
      expression: >-
        variables.appContainers.all(c,
          has(c.securityContext) &&
          has(c.securityContext.runAsNonRoot) &&
          c.securityContext.runAsNonRoot == true
        )

    - message: 'hostPath volumes are not allowed'
      expression: >-
        !has(object.spec.volumes) ||
        object.spec.volumes.all(v, !has(v.hostPath))

    - message: 'Images must use immutable digest (sha256)'
      expression: >-
        variables.appContainers.all(c,
          c.image.contains('@sha256:')
        )

    - message: 'Default service account must not be used'
      expression: >-
        has(object.spec.serviceAccountName) &&
        object.spec.serviceAccountName != "default"

    - message: 'Memory requests and limits are required, CPU requests required'
      expression: >-
        variables.appContainers.all(c,
          has(c.resources) &&
          has(c.resources.requests) &&
          has(c.resources.requests.memory) &&
          has(c.resources.requests.cpu) &&
          has(c.resources.limits) &&
          has(c.resources.limits.memory)
        )

    - message: 'Host network access is not allowed'
      expression: >-
        !has(object.spec.hostNetwork) ||
        object.spec.hostNetwork == false

    - message: 'Host PID access is not allowed'
      expression: >-
        !has(object.spec.hostPID) ||
        object.spec.hostPID == false

    - message: 'Privilege escalation is not allowed'
      expression: >-
        variables.appContainers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.allowPrivilegeEscalation) ||
          c.securityContext.allowPrivilegeEscalation == false
        )

    # - message: 'Seccomp profile must be RuntimeDefault'
    #   expression: >-
    #     has(object.spec.securityContext) &&
    #     has(object.spec.securityContext.seccompProfile) &&
    #     object.spec.securityContext.seccompProfile.type == "RuntimeDefault"

    - message: 'Capabilities must not be added, ALL must be dropped'
      expression: >-
        variables.appContainers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.capabilities) ||
          (
            !has(c.securityContext.capabilities.add) &&
            has(c.securityContext.capabilities.drop) &&
            c.securityContext.capabilities.drop.exists(d, d == "ALL")
          )
        )