apiVersion: policies.kyverno.io/v1
kind: NamespacedValidatingPolicy
metadata:
  name: restrict-image-registries
  namespace: petclinic
spec:
  webhookConfiguration:
    timeoutSeconds: 15
  evaluation:
    admission:
      enabled: true
    background:
      enabled: false
    mode: Kubernetes
  validationActions: [Deny]
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE', 'UPDATE']
        resources: ['pods']

  variables:
    - name: allowedRegistries
      expression: >-
        [
          "509194952955.dkr.ecr.us-east-2.amazonaws.com/springboot/",
          "docker.io/istio/",
          "gcr.io/istio-release/"
        ]

    validations:
        - message: 'Image must be from an approved registry'
        messageExpression: >-
            "Container '" + c.name + "' uses image '" + c.image + 
            "' which is not from an approved registry. Allowed: ECR springboot, docker.io/istio/, gcr.io/istio-release/"
        expression: >-
            object.spec.containers.all(c,
            variables.allowedRegistries.exists(r, c.image.startsWith(r))
            )

        - message: 'Init container image must be from an approved registry'
        messageExpression: >-
            "Init container '" + c.name + "' uses image '" + c.image +
            "' which is not from an approved registry. Allowed: ECR springboot, docker.io/istio/, gcr.io/istio-release/"
        expression: >-
            !has(object.spec.initContainers) ||
            object.spec.initContainers.all(c,
            variables.allowedRegistries.exists(r, c.image.startsWith(r))
            )