apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: {{ .Values.namespaces.app }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespaces.kubeSystem }}
        - podSelector:          
            matchLabels:
              k8s-app: kube-dns # verify this shit
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP