apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-istio-controlplane
  namespace: {{ .Values.namespaces.app }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespaces.istioSystem }}
      ports:
        - port: 15012    # xDS - Envoy gets routing rules from istiod
        - port: 15014    # istiod monitoring
        - port: 15017    # istiod webhook
        - port: 443      # istio webhook
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespaces.istioSystem }}
      ports:
        - port: 15090    # Envoy metrics scraping
        - port: 15000    # Envoy admin port
        - port: 15020    # Istio agent metrics