apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: config-server-netpol
  namespace: {{ .Values.namespaces.app }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.matchLabels.configServer }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: {{ .Values.ports.configServer }}
