apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-gateway-netpol
  namespace: {{ .Values.namespaces.app }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.matchLabels.apiGateway }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespaces.istioIngress }}
          podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.istioIngressGateway }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.customersService }}
      ports:
        - port: {{ .Values.ports.customersService }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.visitsService }}
      ports:
        - port: {{ .Values.ports.visitsService }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.vetsService }}
      ports:
        - port: {{ .Values.ports.vetsService }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.genaiService }}
      ports:
        - port: {{ .Values.ports.genaiService }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.discoveryServer }}
      ports:
        - port: {{ .Values.ports.discoveryServer }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.configServer }}
      ports:
        - port: {{ .Values.ports.configServer }}