apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: customers-service-netpol
  namespace: {{ .Values.namespaces.app }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.matchLabels.customersService }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.apiGateway }}
      ports:
        - port: {{ .Values.ports.apiGateway }}
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.adminServer }}
      ports:
        - port: {{ .Values.ports.adminServer }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.configServer }}
      ports:
        - port: {{ .Values.ports.configServer }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.discoveryServer }}
      ports:
        - port: {{ .Values.ports.discoveryServer }}
    - to:
        - ipBlock:
            cidr: {{ .Values.rds.cidr }}
      ports:
        - port: {{ .Values.ports.rdsMysql }}