apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: admin-server-netpol
  namespace: {{ .Values.namespaces.app }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.matchLabels.adminServer }}
  policyTypes:
    - Ingress 
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: {{ .Values.ports.adminServer }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.configServer }}
      ports:
        - port: {{ .Values.ports.configServer }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.matchLabels.discoveryServer }}
      ports:
        - port: {{ .Values.ports.discoveryServer }}