createNamespace: false
namespace: petclinic

container:
  name: api-gateway
  port: 8080
  readinessProbe:
    path: /actuator/health
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  livenessProbe:
    path: /actuator/health
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m

selectorLabels:
  app: api-gateway

image:
  repository: 509194952955.dkr.ecr.us-east-2.amazonaws.com/springboot/api-gateway
  tag: 'c84d2ef1'
  digest: sha256:85387b676751d39ead9de1a74a2acc29ca0a60acb782a686bf16bf8a87675376

serviceAccount:
  enabled: false

secretStore:
  enabled: false

externalSecret:
  enabled: false

databaseMigration:
  enabled: false

deployment:
  enabled: false

argoRollout:
  enabled: true
  name: api-gateway-rollout
  replicas: 2
  env:
    plain:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_URL: http://config-server:8888
  minReadySeconds: 30
  revisionHistoryLimit: 5
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      dynamicStableScale: true
      abortScaleDownDelaySeconds: 600

service:
  enabled: true
  name: api-gateway
  port: 8080
  rolloutServices:
    enabled: true
    stableService: api-gateway
    canaryService: api-gateway-canary-service
    
virtualService:
  enabled: true
  name: api-gateway-vs
  gatewayRef:
    enabled: true
    namespace: istio-ingress
    name: petclinic-gateway
  http:
    route: primary
  hosts:
    - petclinic-dev.lefrancis.org
