image:
  repository: 509194952955.dkr.ecr.us-east-2.amazonaws.com/dev-springboot/config-server
  tag: '0c2c74af'
  digest: 509194952955.dkr.ecr.us-east-2.amazonaws.com/dev-springboot/config-server@sha256:63d0e9bcf69d82e3fed1bd850c12a3ce48f022c13dfb95fbdf821aa98747bfd5
