namespace: petclinic

container:
  name: config-server
  port: 8888
  readinessProbe:
    path: /
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  livenessProbe:
    path: /
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m

selectorLabels:
  app: config-server

image:
  repository: 509194952955.dkr.ecr.us-east-2.amazonaws.com/springboot/config-server
  tag: '6af97245'
  digest: sha256:d4b846f277c18ff3ec68b37ef3479f56a159753ce57eb0ac3ed7b951665659db
serviceAccount:
  enabled: true
  name: config-server-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-config-server-sa-pod-secrets-reader"

secretStore:
  enabled: true
  name: config-server-secretStore
  awsRegion: us-east-2

externalSecret:
  enabled: true
  name: config-server-externalSecret
  refreshInterval: "5m"
  target:
    name: config-server-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_HOST
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_USER
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_DATABASE

databaseMigration:
  enabled: false

deployment:
  enabled: true
  name: config-server-deployment
  replicas: 2
  env:
    secrets:
      - name: MYSQL_HOST
        secretName: config-server-secrets
        secretKey: MYSQL_HOST
      - name: MYSQL_USER
        secretName: config-server-secrets
        secretKey: MYSQL_USER
      - name: MYSQL_PASSWORD
        secretName: config-server-secrets
        secretKey: MYSQL_PASSWORD
      - name: MYSQL_DATABASE
        secretName: config-server-secrets
        secretKey: MYSQL_DATABASE
    plain:
      SPRING_PROFILES_ACTIVE: native
      CONFIG_DIR: /config
  minReadySeconds: 30
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0

argoRollout:
  enabled: false

service:
  enabled: true
  name: config-server
  port: 8888
  rolloutServices:
    enabled: false

virtualService:
  enabled: false

