createNamespace: false
namespace: petclinic

container:
  name: customers-service
  port: 8081
  readinessProbe:
    path: /actuator/health
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  livenessProbe:
    path: /actuator/health
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m

selectorLabels:
  app: customers-service

image:
  repository: 509194952955.dkr.ecr.us-east-2.amazonaws.com/springboot/customers-service
  tag: 'c84d2ef1'
  digest: sha256:8283c6b7289dcbaa385ee9e3cc2bbd341f619a54407bd649b0257d140efa840d

serviceAccount:
  enabled: true
  name: customers-service-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-customers-service-sa-pod-secrets-reader"

secretStore:
  enabled: true
  kind: SecretStore
  name: customers-service-secret-store
  awsRegion: us-east-2

externalSecret:
  enabled: true
  name: customers-service-external-secret
  refreshInterval: "5m"
  target:
    name: customers-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_HOST
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_USER
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_DATABASE

databaseMigration:
  enabled: false

deployment:
  enabled: false

argoRollout:
  enabled: true
  name: customers-service-rollout
  replicas: 2
  env:
    secrets:
      - name: MYSQL_HOST
        secretName: customers-service-secrets
        secretKey: MYSQL_HOST
      - name: MYSQL_USER
        secretName: customers-service-secrets
        secretKey: MYSQL_USER
      - name: MYSQL_PASSWORD
        secretName: customers-service-secrets
        secretKey: MYSQL_PASSWORD
      - name: MYSQL_DATABASE
        secretName: customers-service-secrets
        secretKey: MYSQL_DATABASE
    plain:
      SPRING_PROFILES_ACTIVE: docker,mysql
      CONFIG_SERVER_URL: http://config-server:8888
  minReadySeconds: 30
  revisionHistoryLimit: 5
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      dynamicStableScale: true
      abortScaleDownDelaySeconds: 600

service:
  enabled: true
  name: customers-service
  port: 8081
  rolloutServices:
    enabled: true
    stableService: customers-service
    canaryService: customers-service-canary
    
virtualService:
  enabled: true
  name: customers-service-vs
  gatewayRef:
    enabled: false
  http:
    route: primary
  hosts:
    - customers-service
