createNamespace: false
namespace: petclinic
container:
  name: discovery-server
  port: 8761
  readinessProbe:
    path: /
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  livenessProbe:
    path: /
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m
selectorLabels:
  app: discovery-server
image:
  repository: 509194952955.dkr.ecr.us-east-2.amazonaws.com/springboot/discovery-server
  tag: 'd3c821db'
  digest: sha256:d1e5de2c2e5c9565844944106eb15cf0bc445a6c8650136f41f452f812480873
serviceAccount:
  enabled: false
secretStore:
  enabled: false
externalSecret:
  enabled: false
databaseMigration:
  enabled: false
deployment:
  enabled: true
  name: discovery-server-deployment
  replicas: 2
  env:
    plain:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_URL: http://config-server
  minReadySeconds: 30
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
service:
  enabled: true
  name: discovery-server
  port: 8761
  rolloutServices:
    enabled: false
virtualService:
  enabled: false
