createNamespace: false
namespace: petclinic

container:
  name: genai-service
  port: 8084
  readinessProbe:
    path: /
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  livenessProbe:
    path: /
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m

selectorLabels:
  app: genai-service

image:
  repository: 509194952955.dkr.ecr.us-east-2.amazonaws.com/springboot/genai-service
  tag: 'c84d2ef1'
  digest: sha256:cda8f4c5ae6b4b90398938988997b0a78692c8aca63df6f61f643f5e249101a8

serviceAccount:
  enabled: true
  name: genai-service-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-genai-service-sa-pod-secrets-reader"

secretStore:
  enabled: true
  kind: SecretStore
  name: genai-service-secret-store
  awsRegion: us-east-2

externalSecret:
  enabled: true
  name: genai-service-external-secret
  refreshInterval: "5m"
  target:
    name: genai-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: dev/springboot-microservices
        property: OPENAI_API_KEY

databaseMigration:
  enabled: false

deployment:
  enabled: false

argoRollout:
  enabled: true
  name: admin-server-rollout
  replicas: 2
  env:
    secrets:
      - name: OPENAI_API_KEY
        secretName: genai-service-secrets
        secretKey: OPENAI_API_KEY
    plain:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_URL: http://config-server:8888
  minReadySeconds: 30
  revisionHistoryLimit: 5
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      dynamicStableScale: true
      abortScaleDownDelaySeconds: 600

service:
  enabled: true
  name: genai-service-service
  port: 8084
  rolloutServices:
    enabled: false
    stableService: genai-service-stable-service
    canaryService: genai-service-canary-service

virtualService:
  enabled: true
  name: genai-service-vs
  gatewayRef:
    enabled: false
  http:
    route: primary
  hosts:
    - genai-service-stable-service
