clusterIssuer:
  enabled: true
  email: "silas@lefrancis.org"
  existingSecret:
    name: "platform-security-secrets"
    key: "cloudflare-api-token"

externalSecret:
  enabled: true
  data: 
    - secretKey: slack_webhook_url
      remoteRef:
        key: "" 
        property: slack_webhook_url
    - secretKey: api-token
      remoteRef:
        key: "" 
        property: cloudflare-api-token