clusterPolicy:
  network:
    istioIngress:
      label: istio-ingressgateway
      namespace: istio-ingress

    rds:
      cidr: "10.0.1.50/32"
      port: 3306

    prometheus:
      label: prometheus
      namespace: monitoring
      port: 8080

  kyverno:
    ecr:
      accountId: "509194952955"
      region: "us-east-2"
      prefix: ""

    github:
      org: "silasfrancis"
      repo: ""
      branch: ""
      tokenIssuer: https://token.actions.githubusercontent.com
      authorizedWorkflows:
        - build-push.yaml
        - build-migrations.yaml