apiVersion: policies.kyverno.io/v1
kind: NamespacedImageValidatingPolicy
metadata:
  name: validate-image-signatures
  namespace: {{ .Values.namespaces.app }}
spec:
  webhookConfiguration:
    timeoutSeconds: {{ .Values.spec.webhook.timeoutSeconds }}
  evaluation:
    background:
      enabled: false
  validationActions: {{ .Values.spec.validationActions }}
  failurePolicy: Fail
  validationConfigurations:
    mutateDigest: true
    required: true
    verifyDigest: true
  matchConstraints:                          
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']                 
        operations: ['CREATE', 'UPDATE']
        resources: ['pods']
  credentials:
    allowInsecureRegistry: false
    providers:
      - amazon
  matchImageReferences:
    - glob: '{{ .Values.ecr.accountId }}.dkr.ecr.{{ .Values.ecr.region }}.amazonaws.com/{{ .Values.ecr.prefix }}/*'
  attestors:
    - name: cosign-app-build-attestor
      cosign:
        keyless:
          identities:
            - subject: 'https://github.com/{{ .Values.github.org   }}/{{ .Values.github.repo }}/.github/workflows/{{ .Values.github.workflowRef.buildPush }}@refs/heads/{{ .Values.github.branch }}'
              issuer: '{{ .Values.github.tokenIssuer }}'
        ctlog:
          url: 'https://rekor.sigstore.dev'
    - name: cosign-migration-build-attestor
      cosign:
        keyless:
          identities:
            - subject: 'https://github.com/{{ .Values.github.org   }}/{{ .Values.github.repo }}/.github/workflows/{{ .Values.github.workflowRef.buildMigrations }}@refs/heads/{{ .Values.github.branch }}'
              issuer: '{{ .Values.github.tokenIssuer }}'
        ctlog:
          url: 'https://rekor.sigstore.dev'

  # attestations:                             
  #   - name: cosignAttestation
  #     intoto:
  #       type: cosign.sigstore.dev/attestation/vuln/v1

  validations:
    - message: 'Container image must be signed by either the app or migration build workflow'
      expression: >-
        images.containers.map(image,
          verifyImageSignatures(image, [attestors["cosign-app-build-attestor"]]) > 0 ||
          verifyImageSignatures(image, [attestors["cosign-migration-build-attestor"]]) > 0
        ).all(e, e)

    - message: 'Init container image must be signed by either the app or migration build workflow'
      expression: >-
        !has(object.spec.initContainers) ||
        images.initContainers.map(image,
          verifyImageSignatures(image, [attestors["cosign-app-build-attestor"]]) > 0 ||
          verifyImageSignatures(image, [attestors["cosign-migration-build-attestor"]]) > 0
        ).all(e, e)

    # - message: 'Image must have a valid vulnerability scan attestation'
    #   expression: >-
    #     images.containers.map(image,
    #       verifyAttestationSignatures(image, attestations.cosignAttestation,
    #         [attestors["cosign-app-build-attestor"]])
    #     ).all(e, e > 0)