apiVersion: policies.kyverno.io/v1
kind: NamespacedImageValidatingPolicy
metadata:
  name: validate-image-signatures
  namespace: {{ .Values.namespaces.app }}
spec:
  webhookConfiguration:
    timeoutSeconds:
  evaluation:
    background:
      enabled: false
  validationActions: 
  failurePolicy: Fail
  validationConfigurations:
    mutateDigest: true
    required: true
    verifyDigest: true
  matchConstraints:                          
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']                 
        operations: ['CREATE', 'UPDATE']
        resources: ['pods']
  credentials:
    allowInsecureRegistry: false
    providers:
      - amazon
  matchImageReferences:
    - glob: {{ include "kyverno.ecr.glob" . | quote }}
  
  attestors:
    {{- include "kyverno.attestors.list" . | nindent 4 }}

  # attestations:                             
  #   - name: cosignAttestation
  #     intoto:
  #       type: cosign.sigstore.dev/attestation/vuln/v1

  validations:
    - message: 'Container Images must be signed by an authorized GitHub workflow'
      expression: >-
        images.containers.map(image,
          {{ include "kyverno.attestations.expression" . }}
        ).all(e, e)

    - message: 'Init container image must be signed by either the app or migration build workflow'
      expression: >-
        !has(object.spec.initContainers) ||
        images.initContainers.map(image,
          {{ include "kyverno.attestations.expression" . }}
        ).all(e, e)

    # - message: 'Image must have a valid vulnerability scan attestation'
    #   expression: >-
    #     images.containers.map(image,
    #       verifyAttestationSignatures(image, attestations.cosignAttestation,
    #         [attestors["cosign-app-build-attestor"]])
    #     ).all(e, e > 0)

