apiVersion: policies.kyverno.io/v1
kind: NamespacedMutatingPolicy
metadata:
  name: mutation-defaults
  namespace: {{ .Values.namespaces.app }}
spec:
  evaluation:
    admission:
      enabled: true
    mutateExisting:
      enabled: false
  webhookConfiguration:
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]

  mutations:
    # Add environment label
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >-
          !has(object.metadata.labels) || !has(object.metadata.labels.environment)
          ? Object{
              metadata: Object.metadata{
                labels: (has(object.metadata.labels) ? object.metadata.labels : {})
                  + {"environment": "{{ .Values.environment }}"}
              }
            }
          : object

    # Container level security defaults
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >-
            Object{
            spec: Object.spec{
                containers: object.spec.containers.map(c,
                Object.spec.containers{
                    name: c.name,
                    securityContext:
                    (has(c.securityContext) ? c.securityContext : {})
                    + {
                        "runAsNonRoot": true,
                        "privileged": false,
                        "allowPrivilegeEscalation": false,
                        "readOnlyRootFilesystem": true,

                        "capabilities":
                            (has(c.securityContext) && has(c.securityContext.capabilities)
                            ? c.securityContext.capabilities
                            : {})
                            + {
                                "drop": ["ALL"]
                            },

                        "seccompProfile":
                            (has(c.securityContext) && has(c.securityContext.seccompProfile)
                            ? c.securityContext.seccompProfile
                            : {})
                            + {
                                "type": "RuntimeDefault"
                            }
                        }
                }
                )
            }
            }

    # Pod-level security defaults
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >-
          Object{
            spec: Object.spec{
              hostNetwork: false,
              hostPID: false,
              hostIPC: false,
              securityContext: 
              has(object.spec.securityContext) ? object.spec.securityContext : {}
              + {
                "runAsNonRoot": true,
                "seccompProfile":
                  (has(object.spec.securityContext) && has(object.spec.securityContext.seccompProfile)
                  ? object.spec.securityContext.seccompProfile : {})
                  + {
                    "type": "RuntimeDefault"
                  }  
              }
            }
          }