{{- range $nsName, $nsConfig := .Values.clusterPolicy.managedNamespaces }}
{{- if $nsConfig.kyvernoStatic }}
---
apiVersion: policies.kyverno.io/v1
kind: NamespacedValidatingPolicy
metadata:
  name: pod-security
  namespace: {{ $nsName }}
  labels:
    {{- include "policies.kyverno.labels" $ | nindent 4 }}
spec:
  webhookConfiguration:
    timeoutSeconds: 3
  evaluation:
    admission:
      enabled: true
    background:
      enabled: false
    mode: Kubernetes
  validationActions: [Deny]
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE', 'UPDATE']
        resources: ['pods']

  variables:
    - name: appContainers
      expression: >-
        object.spec.containers.filter(c,
          !c.image.contains('istio-proxy') &&
          !c.image.contains('istio-pilot')
        )

  validations:
    - message: 'Privileged containers or host access (Network/PID/IPC) not allowed'
      expression: >-
        variables.appContainers.all(c, 
          !has(c.securityContext) || !has(c.securityContext.privileged) || c.securityContext.privileged == false
        ) &&
        (!has(object.spec.hostNetwork) || object.spec.hostNetwork == false) &&
        (!has(object.spec.hostPID) || object.spec.hostPID == false) &&
        (!has(object.spec.hostIPC) || object.spec.hostIPC == false)

    - message: 'Containers must run as non-root (check Pod or Container level)'
      expression: >-
        variables.appContainers.all(c,
          (has(c.securityContext) && c.securityContext.runAsNonRoot == true) ||
          (has(object.spec.securityContext) && object.spec.securityContext.runAsNonRoot == true)
        )

    - message: 'hostPath volumes and default service accounts are forbidden'
      expression: >-
        (!has(object.spec.volumes) || object.spec.volumes.all(v, !has(v.hostPath))) &&
        (has(object.spec.serviceAccountName) && object.spec.serviceAccountName != "default")

    - message: 'Resources: Memory limits and CPU/Memory requests are required'
      expression: >-
        variables.appContainers.all(c,
          has(c.resources.requests.memory) &&
          has(c.resources.requests.cpu) &&
          has(c.resources.limits.memory)
        )

    - message: 'Security: Privilege escalation forbidden and ALL capabilities must be dropped'
      expression: >-
        variables.appContainers.all(c,
          (!has(c.securityContext.allowPrivilegeEscalation) || c.securityContext.allowPrivilegeEscalation == false) &&
          has(c.securityContext.capabilities.drop) &&
          c.securityContext.capabilities.drop.exists(d, d == "ALL") &&
          !has(c.securityContext.capabilities.add)
        )
{{- end }}
{{- end }}