apiVersion: policies.kyverno.io/v1
kind: NamespacedValidatingPolicy
metadata:
  name: protect-networkpolicy-deletion
  namespace: {{ .Values.namespaces.app }}
spec:
  webhookConfiguration:
    timeoutSeconds: {{ .Values.spec.webhook.timeoutSeconds }}
  validationActions: {{ .Values.spec.validationActions }}
  matchConstraints:
    resourceRules:
      - apiGroups: ['networking.k8s.io']
        apiVersions: ['v1']
        operations: ['DELETE']
        resources: ['networkpolicies']
  validations:
    - message: 'Protected NetworkPolicies cannot be deleted'
      expression: >-
        !has(object.metadata.labels) ||
        !has(object.metadata.labels.protected) ||
        object.metadata.labels.protected != "true"