{{- $kyv := .Values.clusterPolicy.kyverno -}}
{{- range $nsName, $nsConfig := .Values.clusterPolicy.managedNamespaces }}
{{- if $nsConfig.kyvernoStatic }}
---
apiVersion: policies.kyverno.io/v1
kind: NamespacedValidatingPolicy
metadata:
  name: restrict-image-registries
  namespace: {{ $nsName }}
  labels:
    {{- include "policies.kyverno.labels" $ | nindent 4 }}
spec:
  webhookConfiguration:
    timeoutSeconds: 15
  evaluation:
    admission: { enabled: true }
  validationActions: [Deny]
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE', 'UPDATE']
        resources: ['pods']

  variables:
    - name: allowedRegistries
      expression: >-
        [
          "{{ include "kyverno.ecr.glob" $ | replace "*" "" }}", 
          "docker.io/istio/",
          "gcr.io/istio-release/",
          "quay.io/kiwigrid/"
        ]

  validations:
    - message: 'Image must be from an approved registry'
      expression: >-
        object.spec.containers.all(c,
          variables.allowedRegistries.exists(r, c.image.startsWith(r))
        )
{{- end }}
{{- end }}