apiVersion: policies.kyverno.io/v1
kind: NamespacedValidatingPolicy
metadata:
  name: pod-security
  namespace: {{ .Values.namespaces.app }}
spec:
  webhookConfiguration:
    timeoutSeconds: {{ .Values.spec.webhook.timeoutSeconds }}
  evaluation:
    admission:
      enabled: true
    background:
      enabled: false
    mode: Kubernetes
  validationActions: {{ .Values.spec.validationActions }}
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ['networking.k8s.io']
        apiVersions: ['v1']
        operations: ['CREATE', 'UPDATE']
        resources: ['networkpolicies']
    validations:
    - message: 'NetworkPolicies must have a "protected" label with value "true" or "false"'
        expression: >-
        has(object.metadata.labels) &&
        has(object.metadata.labels.protected) &&
        (
            object.metadata.labels.protected == "true" ||
            object.metadata.labels.protected == "false"
        )