{{- $kyv := .Values.clusterPolicy.kyverno -}}
{{- range $nsName, $nsConfig := .Values.clusterPolicy.managedNamespaces }}
{{- if $nsConfig.kyvernoImageVerify }}
---
apiVersion: policies.kyverno.io/v1
kind: NamespacedImageValidatingPolicy
metadata:
  name: verify-image-provenance
  namespace: {{ $nsName }}
  labels:
    {{- include "policies.kyverno.labels" $ | nindent 4 }}
spec:
  webhookConfiguration:
    timeoutSeconds: 15
  evaluation:
    admission:
      enabled: true
    background:
      enabled: false
    mode: Kubernetes
  validationActions: [Deny]
  failurePolicy: Fail
  validationConfigurations:
    mutateDigest: true
    required: true
    verifyDigest: true
  matchConstraints:                          
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']                  
        operations: ['CREATE', 'UPDATE']
        resources: ['pods']
  credentials:
    allowInsecureRegistry: false
    providers:
      - amazon
  matchImageReferences:
    - glob: {{ include "kyverno.ecr.glob" $ | quote }}
  
  attestors:
    {{- include "kyverno.attestors.list" $ | nindent 4 }}

  attestations:
    - name: vulnScan
      intoto:
        type: cosign.sigstore.dev/attestation/vuln/v1

  validations:
    - message: 'Container Images must be signed by an authorized GitHub workflow'
      expression: >-
        images.containers.map(image,
          {{ include "kyverno.attestations.expression" $ }}
        ).all(e, e)

    - message: 'Init container image must be signed by an authorized GitHub workflow'
      expression: >-
        !has(object.spec.initContainers) ||
        images.initContainers.map(image,
          {{ include "kyverno.attestations.expression" $ }}
        ).all(e, e)

    - message: "Container Images must have a verified vulnerability scan attestation from an authorized GitHub workflow."
      expression: >-
        images.containers.map(image,
          {{ include "kyverno.attestations.validation.expression" $ }}
        ).all(e, e)

    - message: "Init container image must have a verified vulnerability scan attestation from an authorized GitHub workflow."
      expression: >-
        !has(object.spec.initContainers) ||
        images.initContainers.map(image,
          {{ include "kyverno.attestations.validation.expression" $ }}
        ).all(e, e)
{{- end }}
{{- end }}