{
 "title": "Istio / Traffic Dashboard",
 "description": "Istio / Traffic Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(istio_requests_total,destination_service_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(istio_requests_total{destination_service_namespace=~\"$namespace\"},destination_service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Traffic volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request volume per virtual service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (\r\n  rate(istio_requests_total{\r\n    reporter=\"destination\",\r\n    destination_service_namespace=~\"$namespace\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Istio error rate (Envoy-side)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (\r\n  rate(istio_requests_total{\r\n    reporter=\"destination\",\r\n    destination_service_namespace=~\"$namespace\",\r\n    response_code=~\"5.*\"\r\n  }[$__rate_interval])\r\n)\r\n/\r\nsum by (destination_service_name) (\r\n  rate(istio_requests_total{\r\n    reporter=\"destination\",\r\n    destination_service_namespace=~\"$namespace\"\r\n  }[$__rate_interval])\r\n) * 100",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Retries per service",
   "type": "timeseries",
   "description": "Retries per service\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (\r\n  rate(envoy_cluster_upstream_rq_retry{\r\n    namespace=~\"$namespace\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream connection errors",
   "type": "timeseries",
   "description": "Upstream connection errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (\r\n  rate(istio_requests_total{\r\n    reporter=\"destination\",\r\n    destination_service_namespace=~\"$namespace\",\r\n    response_flags=~\"UC|UF|UH|UR\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeouts per service",
   "type": "timeseries",
   "description": "Timeouts per service",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (\r\n  rate(istio_requests_total{\r\n    reporter=\"destination\",\r\n    destination_service_namespace=~\"$namespace\",\r\n    response_code=\"0\",\r\n    response_flags=~\"UT|UO\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit breaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Circuit breaker state",
     "type": "stat",
     "description": "Circuit breaker state",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (destination_service_name) (\r\n  rate(istio_requests_total{\r\n    reporter=\"destination\",\r\n    destination_service_namespace=~\"$namespace\",\r\n    response_flags=\"UO\"\r\n  }[$__rate_interval])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "mTLS success/failure rate",
     "type": "timeseries",
     "description": "mTLS success/failure rate\n",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum by (destination_service_name) (\r\n  rate(istio_requests_total{\r\n    reporter=\"destination\",\r\n    destination_service_namespace=~\"$namespace\",\r\n    connection_security_policy=\"mutual_tls\"\r\n  }[$__rate_interval])\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (destination_service_name) (\r\n  rate(istio_requests_total{\r\n    reporter=\"destination\",\r\n    destination_service_namespace=~\"$namespace\",\r\n    connection_security_policy!=\"mutual_tls\"\r\n  }[$__rate_interval])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}