{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: {{ .Values.secretStore.kind }}
metadata:
  name: {{ .Values.secretStore.name }}
  {{- if eq .Values.secretStore.kind "SecretStore" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  {{- with .Values.secretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
{{- end }}