{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "microservice.secretStoreName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "microservice.serviceAccountName" . }}
{{- end }}