appName: admin-server
containerPort: 9090
springProfile: docker
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/admin-server
  tag: "f9060456"
  digest: "sha256:7df85f78962f15df418a61b3fb284ba8d480dc676b4a3e4f658d94528b7409df"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 9090
  targetPort: 9090
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
