appName: admin-server
containerPort: 9090
springProfile: docker
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/admin-server
  tag: "df2148c2"
  digest: "sha256:7c9f87bd7256c24b12970e0a18135e0d38b7d15c9a59f75541c529a32030ed51"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 9090
  targetPort: 9090
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
