appName: config-server
containerPort: 8888
springProfile: native
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/config-server
  tag: "ff3b7812"
  digest: "sha256:70a93ba354bef95478dbd2032a55d68aea7601a6abc5ddf595156250f684cd43"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 8888
  targetPort: 8888
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
configServer:
  enabled: false
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-config-server-sa-pod-secrets-reader"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: dev/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: dev/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: dev/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: dev/petclinic
        property: mysql_database
env:
  plain:
    CONFIG_DIR: /config
vpa:
  enabled: true
