appName: config-server
containerPort: 8888
springProfile: native

image:
  repository: springboot/config-server
  tag: "c84d2ef1"
  digest: ""
  pullPolicy: IfNotPresent

controller:
  type: deployment

replicaCount: 1

nodeSelector:
  node-type: on-demand

service:
  port: 8888
  targetPort: 8888

podDisruptionBudget:
  enabled: true
  minAvailable: 1

probes:
  startup:
    path: /
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
  liveness:
    path: /
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-config-server-sa-pod-secrets-reader"

secretStore:
  enabled: true

externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: dev/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: dev/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: dev/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: dev/petclinic
        property: mysql_database

env:
  plain:
    CONFIG_DIR: /config


