appName: config-server
containerPort: 8888
springProfile: native
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/config-server
  tag: "df2148c2"
  digest: "sha256:bfe801c48a4238b9a45ef065bc82bdbfb5624e1fe132b85c29e46d1ada5e675e"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 8888
  targetPort: 8888
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
configServer:
  enabled: false
discoveryServer:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-dev-cluster-app-secrets-irsa"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: dev/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: dev/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: dev/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: dev/petclinic
        property: mysql_database
env:
  plain:
    CONFIG_DIR: /config
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
vpa:
  enabled: true
