createNamespace: false
namespace: petclinic

serviceAccount:
  enabled: true
  name: db-migration-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-db-migration-sa-pod-secrets-reader"
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation

secretStore:
  enabled: true
  kind: SecretStore
  name: db-migration-secret-store
  awsRegion: us-east-2
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-9" 
    helm.sh/hook-delete-policy: before-hook-creation

externalSecret:
  enabled: true
  name: db-migration-external-secret
  refreshInterval: "5m"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-8"
    helm.sh/hook-delete-policy: before-hook-creation
  target:
    name: db-migration-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_HOST
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_USER
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: dev/springboot-microservices
        property: MYSQL_DATABASE

image:
  repository: 509194952955.dkr.ecr.us-east-2.amazonaws.com/springboot/migrations
  tag: '92ea2f34'
  digest: sha256:54b12d351eaf80042e6f97157faaf93d81bc12eec8b933eb5ad5310286320535

container:
  name: db-migration
  imagePullPolicy: Always
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    priviledged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]
  env:
    secrets:
      - name: MYSQL_HOST
        secretName: db-migration-secrets
        secretKey: MYSQL_HOST
      - name: MYSQL_DATABASE
        secretName: db-migration-secrets
        secretKey: MYSQL_DATABASE
      - name: FLYWAY_USER
        secretName: db-migration-secrets
        secretKey: MYSQL_USER
      - name: FLYWAY_PASSWORD
        secretName: db-migration-secrets
        secretKey: MYSQL_PASSWORD
    plain:
      FLYWAY_URL: "jdbc:mysql://$(MYSQL_HOST):3306/$(MYSQL_DATABASE)"

databaseMigration:
  enabled: true
  name: db-migration-job
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
  spec: 
    backoffLimit: 3
    restartPolicy: Never
    hostPID: false
    hostIPC: false
    hostNetwork: false
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: "RuntimeDefault"

deployment:
  enabled: false

argoRollout:
  enabled: false

service:
  enabled: false
  rolloutServices:
    enabled: false

virtualService:
  enabled: false

