appName: discovery-server
containerPort: 8761
springProfile: docker
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/discovery-server
  tag: "f9060456"
  digest: "sha256:7763087c695009201780341fa9a4508d228cab3a27ec91c50dd3560d220386d8"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 8761
  targetPort: 8761
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
