appName: genai-service
containerPort: 8084
springProfile: docker,mysql
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/genai-service
  tag: "ff3b7812"
  digest: "sha256:f3b57d45a74bc2e896a28d4bd6b33eec4279b7ea2c5bb9f4e2134c6a2514d4e6"
  pullPolicy: IfNotPresent
controller:
  type: rollout
replicaCount: 1
spot:
  enabled: true
service:
  port: 8084
  targetPort: 8084
scaleObject:
  enabled: true
configServer:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-config-server-sa-pod-secrets-reader"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: dev/petclinic
        property: openai_api_key
virtualService:
  enabled: true
vpa:
  enabled: true
analysisTemplate:
  enabled: true
