appName: genai-service
containerPort: 8084
springProfile: docker,mysql
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/genai-service
  tag: "f9060456"
  digest: "sha256:29144268c3907049995c7850a261f22d0d88d9615b9e5bdfa70cf0bc4f8e0264"
  pullPolicy: IfNotPresent
controller:
  type: rollout
replicaCount: 1
spot:
  enabled: true
service:
  port: 8084
  targetPort: 8084
scaleObject:
  enabled: true
configServer:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-config-server-sa-pod-secrets-reader"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: dev/petclinic
        property: openai_api_key
virtualService:
  enabled: true
vpa:
  enabled: true
analysisTemplate:
  enabled: true
