appName: genai-service
containerPort: 8084
springProfile: docker
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/genai-service
  tag: "df2148c2"
  digest: "sha256:6cd48700a43cb55f28f90ee376b9374dc212120c5590b7875eef6f9172d8bcb7"
  pullPolicy: IfNotPresent
controller:
  type: rollout
replicaCount: 1
spot:
  enabled: true
service:
  port: 8084
  targetPort: 8084
scaleObject:
  enabled: true
configServer:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-dev-cluster-app-secrets-irsa"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: dev/petclinic
        property: openai_api_key
virtualService:
  enabled: true
vpa:
  enabled: true
analysisTemplate:
  enabled: true
destinationRule:
  enabled: true
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
