appName: vets-service
containerPort: 8083
springProfile: docker,mysql
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/vets-service
  tag: "ff3b7812"
  digest: "sha256:1c0db88e63146833b343796640edf7e19c96cd89a9b7cc2acbb697cd90f0e708"
  pullPolicy: IfNotPresent
controller:
  type: rollout
replicaCount: 1
spot:
  enabled: true
service:
  port: 8083
  targetPort: 8083
hpa:
  enabled: true
configServer:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-config-server-sa-pod-secrets-reader"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: dev/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: dev/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: dev/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: dev/petclinic
        property: mysql_database
virtualService:
  enabled: true
vpa:
  enabled: true
analysisTemplate:
  enabled: true
