appName: visits-service
containerPort: 8082
springProfile: docker,mysql
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/visits-service
  tag: "df2148c2"
  digest: "sha256:6010eebf1416a2701d462fe7639c715a1b386adf6e81eb546c5813e56004d8d0"
  pullPolicy: IfNotPresent
controller:
  type: rollout
replicaCount: 1
spot:
  enabled: true
service:
  port: 8082
  targetPort: 8082
hpa:
  enabled: true
configServer:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-dev-cluster-app-secrets-irsa"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: dev/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: dev/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: dev/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: dev/petclinic
        property: mysql_database
virtualService:
  enabled: true
vpa:
  enabled: true
analysisTemplate:
  enabled: true
destinationRule:
  enabled: true
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
