appName: visits-service
containerPort: 8082
springProfile: docker,mysql
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/visits-service
  tag: "ff3b7812"
  digest: "sha256:8f1b2e1fa6b5cb9a00be6fdf6ef37c48f6ec08a3f8acca73fb62b3b0f05eb5c9"
  pullPolicy: IfNotPresent
controller:
  type: rollout
replicaCount: 1
spot:
  enabled: true
service:
  port: 8082
  targetPort: 8082
hpa:
  enabled: true
configServer:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-config-server-sa-pod-secrets-reader"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: dev/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: dev/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: dev/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: dev/petclinic
        property: mysql_database
virtualService:
  enabled: true
vpa:
  enabled: true
analysisTemplate:
  enabled: true
