ingress:
  enabled: true
  gateway: istio-ingress/internal-istio-ingressgateway

  monitoring:
    stacks:
      - name: goldilocks
        host: goldilocks.lefrancis.org
        serviceName: goldilocks-dashboard
        port: 80
 