# Kubernetes bootstrap and platform operations
version: "3"

vars:
  # Values passed at runtime (e.g., task bootstrap ENV=main)
  # Defaulting here just to prevent empty string errors
  ENV: '{{.ENV | default "dev"}}'
  CLUSTER_NAME: '{{.CLUSTER_NAME | default "dev-petclinic-cluster"}}'

env:
  CILIUM_VERSION: "1.19.3"
  METRICS_SERVER_VERSION: "3.12.2"
  ISTIO_VERSION: "1.29.1"
  ARGOCD_VERSION: "v9.5.0"
  ARGO_ROLLOUTS_VERSION: "v2.40.5"

tasks:
  setup_helm_repos:
    desc: "Add helm repos"
    cmds:
      - helm repo add cilium https://helm.cilium.io --force-update
      - helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server --force-update
      - helm repo add istio https://istio-release.storage.googleapis.com/charts --force-update
      - helm repo add fairwinds-stable https://charts.fairwinds.com/stable --force-update
      - helm repo add external-secrets https://charts.external-secrets.io --force-update
      - helm repo update

  install_cilium:
    desc: "Install Cilium"
    cmds:
      - |
        helm upgrade --install cilium cilium/cilium \
          --version {{ .CILIUM_VERSION }} \
          -n kube-system \
          --set cluster.name={{ .CLUSTER_NAME }} \
          --values bootstrap/cilium/values.yaml

  install_metrics_server:
    desc: "Install metrics-server"
    cmds:
      - |
        helm upgrade --install metrics-server metrics-server/metrics-server \
          --version {{ .METRICS_SERVER_VERSION }} \
          -n kube-system \
          --values bootstrap/metrics-server/values.yaml

  install_external_secrets:
    desc: "Install External Secrets"
    cmds:
      - |
        helm upgrade --install external-secrets \
          external-secrets/external-secrets \
          -n external-secrets \
          --create-namespace \
          --wait

  install_vpa:
    desc: "Install VPA (Recommendation mode)"
    cmds:
      - |
        helm upgrade --install vpa fairwinds-stable/vpa \
          -n vpa \
          --create-namespace \
          --set updater.enabled=false \
          --set admissionController.enabled=false \
          --wait

  install_istio_base:
    desc: "Install Istio base"
    cmds:
      - |
        helm upgrade --install istio-base istio/base \
          -n istio-system \
          --create-namespace \
          --version {{ .ISTIO_VERSION }}

  install_istiod:
    desc: "Install Istiod"
    cmds:
      - |
        helm upgrade --install istiod istio/istiod \
          -n istio-system \
          --version {{ .ISTIO_VERSION }}

  install_argocd:
    desc: "Install ArgoCD"
    cmds:
      - helm repo add argo https://argoproj.github.io/argo-helm
      - |
        helm upgrade --install argocd argo/argo-cd \
          --namespace argocd \
          --create-namespace \
          --version {{ .ARGOCD_VERSION }} \
          --set server.extraArgs={--insecure}

  get_argo_pwd:
    desc: Retrieve the initial admin password for ArgoCD
    cmds:
      - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
  
  install_rollouts:
    desc: "Install Argo Rollouts"
    cmds:
      - |
        helm upgrade --install argo-rollouts argo/argo-rollouts \
          --namespace argo-rollouts \
          --create-namespace \
          --version {{ .ARGO_ROLLOUTS_VERSION }}

  deploy_argo_applications:
    desc: "Deploy ArgoCD Applications"
    cmds:
      - |
        helm upgrade --install argocd argocd \
          --namespace argocd \
          --create-namespace \
          --values argocd/values.yaml \
          --values argocd/values/env/{{.ENV}}/values.yaml

  bootstrap:
    desc: "Full cluster bootstrap"
    cmds:
      - task: setup_helm_repos
      - task: install_cilium
      - task: install_metrics_server
      - task: install_external_secrets
      - task: install_vpa
      - task: install_istio_base
      - task: install_istiod
      - task: install_rollouts
      - task: install_argocd
      - task: deploy_argo_applications
