keda:
  nodeSelector:
    node-type: on-demand
  operator:
    name: keda-operator
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  metricsServer:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  prometheus:
    operator:
      enabled: true
      port: 8080
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    
    metricServer:
      enabled: true
      port: 8080
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

    webhooks:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

    rbac:
      create: true
      enabledCustomScaledRefKinds: true

    serviceAccount:
      operator:
        create: true
        name: keda-operator
      metricServer:
        create: true
        name: keda-metrics-server

goldilocks:
  vpa:
    enabled: false
  controller:
    enabled: true

    rbac:
      create: true
      enableArgoproj: true  
    flags:
      on-by-default: false 
    nodeSelector:
      node-type: on-demand

    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
  dashboard:
    enabled: true
    replicaCount: 1
    excludeContainers: "istio-proxy,linkerd-proxy"
    nodeSelector:
      node-type: on-demand
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
    ingress:
      enabled: false
  