clusterPolicy:
  network:
    istioIngress:
      label: public-istio-ingressgateway
      namespace: istio-ingress

    rds:
      cidr: "10.0.11.0/24"
      port: 3306

    prometheus:
      label: prometheus
      namespace: monitoring
      port: 8080

  kyverno:
    ecr:
      accountId: "509194952955"
      region: "us-east-2"
      prefix: "petclinic"

    github:
      org: "silasfrancis"
      repo: "https://github.com/silasfrancis/eks-platform-petclinic"
      branch: "main"
      tokenIssuer: https://token.actions.githubusercontent.com
      authorizedWorkflows:
        - build-push.yaml
        - build-migrations.yaml