kube-prometheus-stack:
  grafana:
    admin:
      existingSecret: "platform-monitoring-secrets"
      userKey: admin-user
      passwordKey: admin-password

  alertmanager:
    alertmanagerSpec:
      secrets:
        - platform-monitoring-secrets
    config:
      global:
        resolve_timeout: 5m
        smtp_smarthost: "smtp.zoho.com:587"
        smtp_from: "alerts@lefrancis.org"
        smtp_auth_username: "silas@lefrancis.org"
        smtp_auth_password_file: /etc/alertmanager/secrets/platform-monitoring-secrets/email-password
        smtp_require_tls: true

prometheus-cloudwatch-exporter:
  serviceAccount:
    create: true
    name: cloudwatch-exporter
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-cloud-watch-exporter-irsa"

loki:
  loki:
    storage:
      bucketNames:
        chunks: "prod-loki-logs-509194952955-us-east-2"
        ruler: "prod-loki-logs-509194952955-us-east-2"
        admin: "prod-loki-logs-509194952955-us-east-2"
  serviceAccount:
    create: true
    name: loki
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-loki-irsa"

secretStore:
  enabled: true
  kind: SecretStore
  awsRegion: us-east-2

externalSecret:
  enabled: true
  name: platform-monitoring-secrets
  refreshInterval: 1h
  target:
    name: platform-monitoring-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: prod/platform-monitoring
        property: grafana-admin-user
    - secretKey: admin-password
      remoteRef:
        key: prod/platform-monitoring
        property: grafana-admin-password
    - secretKey: slack-webhook-url
      remoteRef:
        key: prod/platform-monitoring
        property: slack-webhook-url
    - secretKey: email-password
      remoteRef:
        key: prod/platform-monitoring
        property: email-password

serviceAccount:
  create: true
  name: "platform-monitoring-sa"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-platform-monitoring-secrets-irsa"

ingress:
  enabled: true
  gateway: istio-ingress/internal-istio-ingressgateway

  monitoring:
    stacks:
      - name: grafana
        host: grafana.lefrancis.org
        serviceName: kube-prometheus-stack-grafana
        port: 80
      - name: prometheus
        host: prometheus.lefrancis.org
        serviceName: kube-prometheus-stack-prometheus
        port: 9090
      - name: loki
        host: loki.lefrancis.org
        serviceName: loki-gateway
        port: 80
