environment                 = "main"
aws_region                  = "us-east-2"
app                         = "petclinic"
application_tag             = "petclinic-main"
eks_namespace               = "petclinic"
appregistry_application_tag = ""
