{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- toYaml $.Values.selectorLabels | nindent 8 }}
        {{- with .Values.deployment.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ .Values.containers.image }}
        resources:
          requests:
            {{- toYaml .Values.containers.resources.requests | nindent 12 }}
          limits:
            {{- toYaml .Values.containers.resources.limits | nindent 12 }}
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsUser: 1337
          runAsGroup: 1337
{{- end }}