{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.podDisruptionBudget.name }}
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    {{- with .Values.selectorLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}