{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway 
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- toYaml .Values.gateway.selector | nindent 4 }}
  servers:
    {{- toYaml .Values.gateway.servers | nindent 4 }}
{{- end }}