{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway 
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.selectors }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.servers }}
  servers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}