{{- $net := .Values.clusterPolicy.network -}}
{{- range $nsName, $nsConfig := .Values.clusterPolicy.managedNamespaces }}
{{- if $nsConfig.istio }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-prometheus-scraping
  namespace: {{ $nsName }}
  labels:
    {{- include "policies.istio.labels" $ | nindent 4 }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/{{ $net.prometheus.namespace }}/sa/{{ $net.prometheus.serviceAccount }}"]
      to:
        - operation:
            paths: ["/actuator/prometheus"]
            methods: ["GET"]
{{- end }}
{{- end }}