{{- range $nsName, $nsConfig := .Values.clusterPolicy.managedNamespaces }}
{{- if $nsConfig.istio }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: {{ $nsName }}
  labels:
    {{- include "policies.istio.labels" $ | nindent 4 }}
spec:
  action: DENY
  rules: [{}]
{{- end }}
{{- end }}
