{{- if .Values.gateway.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "gateway.certificateName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  secretName: {{ include "gateway.certificateSecretName" . }}
  issuerRef:
    name: {{ .Values.gateway.certificate.spec.issuerRef.name }}
    kind: {{ .Values.gateway.certificate.spec.issuerRef.kind }}
  dnsNames:
    {{- include "gateway.certificateDnsNames" . | nindent 4 }}
{{- end }}