{{- if .Values.gateway.gateway.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ include "gateway.gatewayName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
  servers:
    {{- include "gateway.servers" . | nindent 4 }}
{{- end }}