{{- if .Values.gateway.loadbalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.loadBalancerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    {{- include "gateway.loadBalancerAnnotations" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
    - name: status-port
      port: 15021
      targetPort: 15021
{{- end }}