{{- range $name, $cfg := .Values.gateways }}
{{- $ctx := dict "name" $name "gw" $cfg "root" $ }}
{{- if $cfg.role.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gateway.resourceName" $ctx }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gateway.labels" $ctx | nindent 4 }}
rules:
  {{- toYaml $.Values.gatewayDefaults.role.rules | nindent 2 }}
{{- end }}
{{- if $cfg.roleBinding.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gateway.resourceName" $ctx }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gateway.labels" $ctx | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gateway.resourceName" $ctx }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gateway.serviceAccountName" $ctx }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}