appName: config-server
containerPort: 8888
springProfile: native

image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: springboot/config-server
  tag: "c84d2ef1"
  digest: ""
  pullPolicy: IfNotPresent

controller:
  type: deployment

replicaCount: 1

service:
  port: 8888
  targetPort: 8888

probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /

configServer:
  enabled: false

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/prod-petclinic-cluster-appSecrets-irsa"

secretStore:
  enabled: true

externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: prod/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: prod/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: prod/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: prod/petclinic
        property: mysql_database

env:
  plain:
    CONFIG_DIR: /config

vpa:
  enabled: true