appName: customers-service
containerPort: 8081
springProfile: docker,mysql

image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: springboot/customers-service
  tag: "c84d2ef1"
  digest: ""
  pullPolicy: IfNotPresent

controller:
  type: rollout

replicaCount: 1

spot:
  enabled: true

service:
  port: 8081
  targetPort: 8081

hpa:
  enabled: true

configServer:
  enabled: true

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/dev-config-server-sa-pod-secrets-reader"

secretStore:
  enabled: true

externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: dev/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: dev/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: dev/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: dev/petclinic
        property: mysql_database

virtualService:
  enabled: true

vpa:
  enabled: true