appName: discovery-server
containerPort: 8761
springProfile: docker

image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: springboot/discovery-server
  tag: "c84d2ef1"
  digest: ""
  pullPolicy: IfNotPresent

controller:
  type: deployment

replicaCount: 1

service:
  port: 8761
  targetPort: 8761

probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /

