appName: genai-service
containerPort: 8084
springProfile: docker,mysql

image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: springboot/genai-service
  tag: "c84d2ef1"
  digest: ""
  pullPolicy: IfNotPresent

controller:
  type: rollout

replicaCount: 1

spot:
  enabled: true

service:
  port: 8084
  targetPort: 8084

scaleObject:
  enabled: true

configServer:
  enabled: true

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/prod-petclinic-cluster-appSecrets-irsa"

secretStore:
  enabled: true

externalSecret:
  enabled: true
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: prod/petclinic
        property: openai_api_key

virtualService:
  enabled: true

vpa:
  enabled: true

analysisTemplate:
  enabled: true