appName: db-migration

databaseMigration:
  enabled: true

image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/migrations
  tag: "c62caca0"
  digest: "sha256:dfc4bd54fc1d0ba9949e2d066abc02ce85263acce20b89292adeab4f69e07183"
  pullPolicy: IfNotPresent
  
controller:
  type: job

replicaCount: 1

service:
  enabled: false

configServer:
  enabled: false

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/prod-petclinic-cluster-app_secrets-irsa"

secretStore:
  enabled: true

externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: prod/petclinic
        property: mysql_host
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: prod/petclinic
        property: mysql_database
    - secretKey: FLYWAY_USER
      remoteRef:
        key: prod/petclinic
        property: mysql_user
    - secretKey: FLYWAY_PASSWORD
      remoteRef:
        key: prod/petclinic
        property: mysql_password

  env:
    plain:
      FLYWAY_URL: "jdbc:mysql://$(MYSQL_HOST):3306/$(MYSQL_DATABASE)"

