# spec:
#   source:
#     targetRevision: main        # ← main branch
#   destination:
#     server: https://kubernetes.default.svc    # ← main cluster (local)
#     namespace: petclinic

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: git@github.com:silasfrancis/spring_boot_micro_services.git
    targetRevision: main
    path: k8s/argocd
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true