{
 "title": "Cluster Overview",
 "description": "Cluster Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total nodes",
   "type": "stat",
   "description": "Total number nodes",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}) + sum(kube_node_status_condition{condition=\"Ready\", status=\"unknown\"}) + sum(kube_node_status_condition{condition=\"Ready\", status=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Breakdown",
   "type": "piechart",
   "description": "Total Nodes ",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"})",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"false\"})",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"unknown\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Firing alerts",
   "type": "stat",
   "description": "Firing alerts",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"})",
     "legendFormat": "{{alertname}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Firing alerts by severity",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (severity)(ALERTS{alertstate=\"firing\"})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "description": "Total Pods",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "{{namespace}}" }
   ]
  },
  {
   "title": "PVC usage",
   "type": "stat",
   "description": "PVC usage",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes)\r\n/\r\n  sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes)\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Node CPU utilization",
   "type": "bargauge",
   "description": "Node CPU utilization",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n)) * 100\r\n\r\n# (1 - avg by (node) (\r\n#   label_replace(\r\n#     rate(node_cpu_seconds_total{mode=\"idle\"}[5m]),\r\n#     \"node\", \"$1\", \"instance\", \"([^:]+):.*\"\r\n#   )\r\n#   * on(node) group_left(node) \r\n#   label_replace(kube_node_info, \"node\", \"$1\", \"internal_ip\", \"(.*)\")\r\n# )) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node memory utilization",
   "type": "bargauge",
   "description": "Node memory utilization",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (\r\n  node_memory_MemAvailable_bytes{instance=~\"$instance\"}\r\n  / node_memory_MemTotal_bytes{instance=~\"$instance\"}\r\n)) * 100\r\n\r\n# (1 - (\r\n#   label_replace(\r\n#     node_memory_MemAvailable_bytes{},\r\n#     \"node\", \"$1\", \"instance\", \"([^:]+):.*\"\r\n#   )\r\n#   /\r\n#   label_replace(\r\n#     node_memory_MemTotal_bytes{},\r\n#     \"node\", \"$1\", \"instance\", \"([^:]+):.*\"\r\n#   )\r\n# ) * on(node) group_left(node)\r\n#   label_replace(kube_node_info, \"node\", \"$1\", \"internal_ip\", \"(.*)\")\r\n# ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node disk utilization",
   "type": "bargauge",
   "description": "Node disk utilization",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (\r\n  node_filesystem_avail_bytes{fstype=\"xfs\", mountpoint=\"/\"}\r\n  / node_filesystem_size_bytes{fstype=\"xfs\", mountpoint=\"/\"}\r\n)) * 100\r\n\r\n# (1 - (\r\n#   label_replace(\r\n#     node_filesystem_avail_bytes{fstype=\"xfs\", mountpoint=\"/\"},\r\n#     \"node\", \"$1\", \"instance\", \"([^:]+):.*\"\r\n#   )\r\n#   /\r\n#   label_replace(\r\n#     node_filesystem_size_bytes{fstype=\"xfs\", mountpoint=\"/\"},\r\n#     \"node\", \"$1\", \"instance\", \"([^:]+):.*\"\r\n#   )\r\n# ) * on(node) group_left(node)\r\n#   label_replace(kube_node_info, \"node\", \"$1\", \"internal_ip\", \"(.*)\")\r\n# ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Network I/O",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\", device!~\"lo|veth.*|cni.*|flannel.*|cilium.*\"}[5m])\r\n\r\n# label_replace(\r\n#   rate(node_network_receive_bytes_total{device!~\"lo|veth.*|cni.*|cilium.*\"}[5m]),\r\n#   \"node\", \"$1\", \"instance\", \"([^:]+):.*\"\r\n# ) * on(node) group_left(node)\r\n#   label_replace(kube_node_info, \"node\", \"$1\", \"internal_ip\", \"(.*)\")",
     "legendFormat": "⬇ {{instance}} {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\", device!~\"lo|veth.*|cni.*|flannel.*|cilium.*\"}[5m])\r\n\r\n# label_replace(\r\n#   rate(node_network_transmit_bytes_total{device!~\"lo|veth.*|cni.*|cilium.*\"}[5m]),\r\n#   \"node\", \"$1\", \"instance\", \"([^:]+):.*\"\r\n# ) * on(node) group_left(node)\r\n#   label_replace(kube_node_info, \"node\", \"$1\", \"internal_ip\", \"(.*)\")",
     "legendFormat": "⬆ {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "PVC usage by namespace",
   "type": "bargauge",
   "description": "PVC usage by namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (namespace, persistentvolumeclaim) (\r\n    kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}\r\n  )\r\n/\r\n  sum by (namespace, persistentvolumeclaim) (\r\n    kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}\r\n  )\r\n) * 100",
     "legendFormat": "{{namespace}} / {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Pod status breakdown",
   "type": "piechart",
   "description": "Pod status breakdown",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\"} == 1)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "count(kube_pod_status_phase{phase=\"Pending\", namespace=~\"$namespace\"} == 1)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "count(kube_pod_status_phase{phase=\"Failed\", namespace=~\"$namespace\"} == 1)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Prometheus Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion rate",
     "type": "timeseries",
     "description": "Ingestion rate",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Time Series",
     "type": "stat",
     "description": "Active Time Series",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "prometheus_tsdb_head_series", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Active Series Trend",
     "type": "timeseries",
     "description": "Active Series Trend",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      { "expr": "prometheus_tsdb_head_series", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Query Latency",
     "type": "timeseries",
     "description": "Query Latency",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\r\n  rate(prometheus_http_request_duration_seconds_bucket[5m])\r\n)",
       "legendFormat": "{{handler}} - {{method}} - {{code}}"
      }
     ]
    }
   ]
  }
 ]
}