namespace: istio-ingress

labels:
  app: istio-ingressgateway
  istio: ingressgateway
  "istio.io/dataplane-mode": "none"

selectors:
  app: istio-ingressgateway
  istio: ingressgateway

serviceAccount:
  name: istio-ingressgateway
  enabled: true

role:
  name: istio-ingressgateway
  enabled: true
  rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

roleBinding:
  name: istio-ingressgateway
  enabled: true

container:
  name: istio-proxy
  image: auto
  env:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  ports:
    - containerPort: 15090
      protocol: TCP
      name: http-envoy-prom

deployment:
  enabled: true
  name: istio-ingressgateway
  annotations:
    inject.istio.io/templates: gateway
    sidecar.istio.io/inject: "true"
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
  labels:
    sidecar.istio.io/inject: "true"

horizontalPodAutoscaler:
  enabled: true
  name: istio-ingressgateway
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

podDisruptionBudget:
  enabled: true
  name: istio-ingressgateway
  minAvailable: 1

loadbalancer:
  enabled: true
  name: istio-ingressgateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "petclinic-dev-istio-nlb"
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-021845a2ee47579d9,subnet-0d277d84a61c8d17e"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0aa67a44e2bb7187c"
    external-dns.alpha.kubernetes.io/managed: "true"
    external-dns.alpha.kubernetes.io/hostname: "petclinic-dev.lefrancis.org"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/ttl: "120"

certificate:
  name: petclinic-dev-tls
  enabled: true
  spec: 
    secretName: petclinic-dev-ingress-certs
    issuerRef:
      name: letsencrypt-cloudflare
      kind: ClusterIssuer
  dnsNames:
    - petclinic-dev.lefrancis.org

gateway:
  name: petclinic-gateway
  enabled: true
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "petclinic-dev.lefrancis.org"
      tls:
        httpsRedirect: true 
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "petclinic-dev.lefrancis.org"
      tls:
        mode: SIMPLE
        credentialName: petclinic-dev-ingress-certs