monitoring:
  namespace: monitoring

petclinic:
  namespace: petclinic

  services:
    - name: api-gateway
      selectorLabels:
        app: api-gateway

    - name: customers-service
      selectorLabels:
        app: customers-service

    - name: visits-service
      selectorLabels:
        app: visits-service

    - name: vets-service
      selectorLabels:
        app: vets-service