{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "platform-ingress.externalDnsExternalSecretName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ include "platform-ingress.externalDnsSecretStoreName" . }}
    kind: SecretStore
  target:
    name: {{ include "platform-ingress.externalDnsSecretName" . }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
  data:
  {{- range .Values.externalSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef: 
      key: {{ .remoteRef.key }}
      property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}