{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "external-dns.externalSecretName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval:  {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ include "external-dns.secretStoreName" . }}
    kind: SecretStore
  target:
    name: {{ include "external-dns.secretName" . }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef: 
      key: {{ .remoteRef.key }}
      property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}