{{- if .Values.esoServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform-ingress.esoServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.esoServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
{{- end }}