{{- if .Values.externalDnsServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-dns.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.externalDnsServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
{{- end }}