{{- if .Values.ClusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "platform-security.ClusterSecretStoreName" . }}
  labels: 
    {{- include "platform-security.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.ClusterSecretStore.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "platform-security.serviceAccountName" . }}
            namespace: {{ .Release.Namespace }}
{{- end }}