{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "platform-security.secretStoreName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-security.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "platform-security.serviceAccountName" . }}
{{- end }}