apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: 
spec:
  provider:
    aws:
      service: SecretsManager
      region: 
      auth:
        jwt:
          serviceAccountRef:
            name: 