apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: 
    kind: SecretStore
  target:
    name: #the k8 secret it will create
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_HOST   # key inside k8 secret
    remoteRef:
      key: #name of secret manager
      property: #secret
  - secretKey: MYSQL_USER
    remoteRef:
      key: 
      property: 
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: 
      property: 
  - secretKey: MYSQL_DATABASE
    remoteRef:
      key: 
      property: 
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: 
      property: 