{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 6 }} 
  template:
    metadata:
      labels:
        {{- toYaml .Values.selectorLabels | nindent 6 }} 
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
          {{- with .Values.deployment.env.secrets }}
          {{- range . }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .secretName }}
                key: {{ .secretKey }}
          {{- end }}
          {{- end }}
          {{- with .Values.deployment.env.plain }}
          {{- range $key, $val := . }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.container.readinessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.container.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.container.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.container.livenessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.container.livenessProbe.failureThreshold }}
          resources:
            limits:
              memory: {{ .Values.container.resources.limits.memory }}
              cpu: {{ .Values.container.resources.limits.cpu }}
            requests:
              memory: {{ .Values.container.resources.requests.memory }}
              cpu: {{ .Values.container.resources.requests.cpu }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- toYaml .Values.selectorLabels | nindent 20 }}  
                topologyKey: kubernetes.io/hostname
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
{{- end }}