{{- if .Values.argoRollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.argoRollout.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 
  selector:
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 4 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.selectorLabels | nindent 4 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          ports:
            - containerPort: {{ .Values.container.port }}
        env:
        {{- if .Values.argoRollout.env.secrets }}
        {{- range .Values.argoRollout.env.secrets }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .secretName }}
              key: {{ .secretKey }}
        {{- end }}
        {{- end }}
        {{- if .Values.argoRollout.env.plain }}
        {{- range $key, $val := .Values.argoRollout.env.plain }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.container.readinessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.container.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.container.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.container.livenessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.container.livenessProbe.failureThreshold }}
          resources:
            limits:
              memory: {{ .Values.container.resources.limits.memory }}
              cpu: {{ .Values.container.resources.limits.cpu }}
            requests:
              memory: {{ .Values.container.resources.requests.memory }}
              cpu: {{ .Values.container.resources.requests.cpu }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- toYaml .Values.selectorLabels | nindent 4 }}  
                topologyKey: kubernetes.io/hostname
  minReadySeconds: {{ .Values.argoRollout.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.argoRollout.revisionHistoryLimit }}
  strategy:
    canary:
      maxSurge: {{ .Values.argoRollout.strategy.canary.maxSurge }}
      maxUnavailable: {{ .Values.argoRollout.strategy.canary.maxUnavailable }}
      dynamicStableScale: {{ .Values.argoRollout.strategy.canary.dynamicStableScale }}
      abortScaleDownDelaySeconds: {{ .Values.argoRollout.strategy.canary.abortScaleDownDelaySeconds }}
      canaryService: {{ .Values.service.rolloutServices.canaryService }}
      stableService: {{ .Values.service.rolloutServices.stableService }}
    #   analysis:
    #     templates:
    #       - templateName: 
    #     startingStep: 2
    #     args:
    #       - name:
    #         value: 
      trafficRouting:
        istio:
          virtualServices:
            - name: {{ .Values.virtualService.strategy.name }}
              routes:
                - {{ .Values.virtualService.http.route }}
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 40
        - pause: { duration: 1m }
        - setWeight: 80
        - pause: { duration: 1m }
        - setWeight: 100
{{- end }}