{{- if .Values.argoRollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.argoRollout.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.argoRollout.spec.replicas }}
  hostPID: {{ .Values.argoRollout.spec.hostPID }}
  hostIPC: {{ .Values.argoRollout.spec.hostIPC }}
  hostNetwork: {{ .Values.argoRollout.spec.hostNetwork }}
  {{- with .Values.argoRollout.spec.securityContext }}
  securityContext:
    runAsNonRoot: {{ .runAsNonRoot }}
    seccompProfile:
      {{- toYaml .seccompProfile.type | nindent 6 }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.selectorLabels | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          imagePullPolicy: {{ .Values.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
          {{- with .Values.container.env.secrets }}
          {{- range . }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .secretName }}
                key: {{ .secretKey }}
          {{- end }}
          {{- end }}
          {{- with .Values.container.env.plain }}
          {{- range $key, $val := . }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.container.readinessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.container.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.container.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.container.livenessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.container.livenessProbe.failureThreshold }}
          resources:
            limits:
              memory: {{ .Values.container.resources.limits.memory }}
              cpu: {{ .Values.container.resources.limits.cpu }}
            requests:
              memory: {{ .Values.container.resources.requests.memory }}
              cpu: {{ .Values.container.resources.requests.cpu }}
          {{- with .Values.container.securityContext }}
          securityContext:
            runAsNonRoot: {{ .runAsNonRoot }}
            runAsUser: {{ .runAsUser }}
            runAsGroup: {{ .runAsGroup }}
            priviledged: {{ .priviledged }}
            allowPrivilegeEscalation: {{ .allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .readOnlyRootFilesystem }}
            capabilities:
              drop: {{ .capabilities.drop | toYaml | nindent 14 }}
          {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- toYaml .Values.selectorLabels | nindent 20 }}  
                topologyKey: kubernetes.io/hostname
  minReadySeconds: {{ .Values.argoRollout.spec.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.argoRollout.spec.revisionHistoryLimit }}
  strategy:
    canary:
      maxSurge: {{ .Values.argoRollout.spec.strategy.canary.maxSurge }}
      maxUnavailable: {{ .Values.argoRollout.spec.strategy.canary.maxUnavailable }}
      dynamicStableScale: {{ .Values.argoRollout.spec.strategy.canary.dynamicStableScale }}
      abortScaleDownDelaySeconds: {{ .Values.argoRollout.spec.strategy.canary.abortScaleDownDelaySeconds }}
      canaryService: {{ .Values.service.rolloutServices.canaryService }}
      stableService: {{ .Values.service.rolloutServices.stableService }}
    #   analysis:
    #     templates:
    #       - templateName: 
    #     startingStep: 2
    #     args:
    #       - name:
    #         value: 
      trafficRouting:
        istio:
          virtualServices:
            - name: {{ .Values.virtualService.name }}
              {{- range .Values.virtualService.spec.http }}
              {{- if eq .name "primary" }}
              routes:
                - {{ .name }}
              {{- end }}
              {{- end }}  
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 40
        - pause: { duration: 1m }
        - setWeight: 80
        - pause: { duration: 1m }
        - setWeight: 100
{{- end }}