{{- if not .Values.service.rolloutServices.enabled and .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- toYaml .Values.selectorLabels | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
{{- end }}
---
{{- if .Values.service.rolloutServices.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.rolloutServices.stableService }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- toYaml .Values.selectorLabels | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
{{- end }}
---
{{- if .Values.service.rolloutServices.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.rolloutServices.canaryService }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- toYaml .Values.selectorLabels | nindent 4 }} 
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
{{- end }}