{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}   
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{- toYaml .Values.virtualService.hosts | nindent 4 }} 
  {{- if .Values.virtualService.gatewayRef.enabled }}      
  gateways:
    -  "{{ .Values.virtualService.gatewayRef.namespace }}/{{ .Values.virtualService.gatewayRef.name }}"    
  {{- end }}              
  http:
    - name: {{ .Values.virtualService.http.route }}
      route:
        - destination:
            host: {{ .Values.service.rolloutServices.stableService }}
            port:
              number: {{ .Values.service.port }}
          weight: 100
        - destination:
            host: {{ .Values.service.rolloutServices.canaryService }}
            port:
              number: {{ .Values.service.port }}
          weight: 0
{{- end }}