{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}   
  namespace: {{ .Values.namespace }}
spec:
  {{- with .Values.virtualService.spec.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.virtualService.spec.gatewayRef.enabled }}      
  gateways:
    {{- toYaml .Values.virtualService.spec.gatewayRef.gateway | nindent 4 }}
  {{- end }} 
  {{- with .Values.virtualService.spec.http }}
  http:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}