{
 "title": "RDS / Database Dashboard",
 "time": { "from": "2026-04-05T13:32:25.790Z", "to": "2026-04-06T01:32:25.790Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
    }
   },
   { "name": "dbinstance" },
   { "name": "db_max_connections" },
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "RDS health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RDS CPU utilization",
   "type": "gauge",
   "description": "RDS CPU utilization",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dbinstance_identifier=~\"$dbinstance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDS Connection Saturation",
   "type": "stat",
   "description": "RDS Connection Saturation",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{dbinstance_identifier=~\"$dbinstance\"}\r\n/ $db_max_connections * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB connections active vs max",
   "type": "timeseries",
   "description": "DB connections active vs max",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{dbinstance_identifier=~\"$dbinstance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_rds_database_connections_average{dbinstance_identifier=~\"$dbinstance\"}\r\n* 0 + $db_max_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": " IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "IOPS",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "aws_rds_read_iops_average{dbinstance_identifier=~\"$dbinstance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_rds_write_iops_average{dbinstance_identifier=~\"$dbinstance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "aws_rds_read_latency_average{dbinstance_identifier=~\"$dbinstance\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "aws_rds_write_latency_average{dbinstance_identifier=~\"$dbinstance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hikari pool per service",
     "type": "timeseries",
     "description": "Hikari pool per service",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{\r\n  namespace=~\"$namespace\",\r\n  pod=~\"$pod\"\r\n}",
       "legendFormat": "__auto"
      },
      {
       "expr": "hikaricp_connections_idle{\r\n  namespace=~\"$namespace\",\r\n  pod=~\"$pod\"\r\n}",
       "legendFormat": "__auto"
      },
      {
       "expr": "hikaricp_connections_pending{\r\n  namespace=~\"$namespace\",\r\n  pod=~\"$pod\"\r\n}",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(hikaricp_connections_timeout_total{\r\n  namespace=~\"$namespace\",\r\n  pod=~\"$pod\"\r\n}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Flyway migrations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful migrations",
     "type": "stat",
     "description": "Flyway successful migrations stats",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flyway_migrations_total{\r\n  namespace=~\"$namespace\",\r\n  pod=~\"$pod\",\r\n  state=\"success\"\r\n}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Migrations Breakdown",
     "type": "table",
     "description": "Migrations Breakdown",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 20 },
     "targets": [
      {
       "expr": "flyway_migrations_total{\r\n  namespace=~\"$namespace\",\r\n  pod=~\"$pod\"\r\n}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pending migrations",
     "type": "stat",
     "description": "Flyway pending migrations stats",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flyway_migrations_total{\r\n  namespace=~\"$namespace\",\r\n  pod=~\"$pod\",\r\n  state=\"pending\"\r\n}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed migrations",
     "type": "stat",
     "description": "Flyway failed migrations stats",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flyway_migrations_total{\r\n  namespace=~\"$namespace\",\r\n  pod=~\"$pod\",\r\n  state=\"failed\"\r\n}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}