ingress:
  enabled: true
  gateway: istio-ingress/ingress-internal-gateway
  autoscaling:
    stacks:
      - name: goldilocks
        host: goldilocks.internal.lefrancis.org
        serviceName: goldilocks-dashboard
        port: 80
