appName: admin-server
containerPort: 9090
springProfile: docker
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/admin-server
  tag: "47beaa21"
  digest: "sha256:db0e65feb22db2c96edbe363944021d2cc4fbf1f14d34408402b341e38b158f2"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 9090
  targetPort: 9090
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
