appName: admin-server
containerPort: 9090
springProfile: docker
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/admin-server
  tag: "255d2a65"
  digest: "sha256:c69c6d71e50afebea2d3f43ce5ce7518b21933da675c2bdb7c2c36f3d4fc7085"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 9090
  targetPort: 9090
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
