appName: api-gateway
containerPort: 8080
springProfile: docker
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/api-gateway
  tag: "ceb3b585"
  digest: "sha256:fdc3c9cfe3cc04b9778e1641ff0c48b72426a26eec225ed8ea772dfb333fcc46"
  pullPolicy: IfNotPresent
controller:
  type: rollout
replicaCount: 1
service:
  port: 8080
  targetPort: 8080
hpa:
  enabled: true
vpa:
  enabled: true
virtualService:
  enabled: true
  host: petclinic.lefrancis.org
  gateway: istio-ingress/ingress-public-gateway
  routes:
    - name: customers-service
      match:
        - uri:
            prefix: /api/customer/
      rewrite:
        uri: /
      route:
        - destination:
            host: customers-service.petclinic.svc.cluster.local
            port:
              number: 8081
    - name: visits-route
      match:
        - uri:
            prefix: /api/visit/
      rewrite:
        uri: /
      route:
        - destination:
            host: visits-service.petclinic.svc.cluster.local
            port:
              number: 8082
    - name: vets-route
      match:
        - uri:
            prefix: /api/vet/
      rewrite:
        uri: /
      route:
        - destination:
            host: vets-service.petclinic.svc.cluster.local
            port:
              number: 8083
    - name: genai-route
      match:
        - uri:
            prefix: /api/genai/
      rewrite:
        uri: /
      route:
        - destination:
            host: genai-service.petclinic.svc.cluster.local
            port:
              number: 8084
analysisTemplate:
  enabled: true
destinationRule:
  enabled: true
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
