appName: config-server
containerPort: 8888
springProfile: native
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/config-server
  tag: "44589ffd"
  digest: "sha256:297dcbf7adaae1f4643b5efbf01c79afa26e7e51856295d55d3a9d120c567712"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 8888
  targetPort: 8888
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
configServer:
  enabled: false
discoveryServer:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-app-secrets-irsa"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: prod/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: prod/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: prod/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: prod/petclinic
        property: mysql_database
env:
  plain:
    CONFIG_DIR: /config
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
vpa:
  enabled: true
