appName: config-server
containerPort: 8888
springProfile: native
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/config-server
  tag: "255d2a65"
  digest: "sha256:0c24abd2584e9c83c8a5f962f1e88a131ba1996a1cbb988191efe22067ed7562"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 8888
  targetPort: 8888
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
configServer:
  enabled: false
discoveryServer:
  enabled: false
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-app-secrets-irsa"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: prod/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: prod/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: prod/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: prod/petclinic
        property: mysql_database
env:
  plain:
    CONFIG_DIR: /config
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
vpa:
  enabled: true
