appName: discovery-server
containerPort: 8761
springProfile: docker
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/discovery-server
  tag: "44589ffd"
  digest: "sha256:0f8ee490099b8f1facabe6742eb4c42fb3a65dfb390ed0b7def4d9d79af74aa9"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 8761
  targetPort: 8761
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
discoveryServer:
  enabled: false