appName: discovery-server
containerPort: 8761
springProfile: docker
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/discovery-server
  tag: "47beaa21"
  digest: "sha256:7947af476b6463eb281f915909d416185b7cb28f93eba54cdf908b2a3e046572"
  pullPolicy: IfNotPresent
controller:
  type: deployment
replicaCount: 1
service:
  port: 8761
  targetPort: 8761
probes:
  startup:
    path: /
  readiness:
    path: /
  liveness:
    path: /
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
