appName: genai-service
containerPort: 8084
springProfile: docker,mysql
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/genai-service
  tag: "28114d47"
  digest: "sha256:6c4634c0bb692131e0711db3149494d32630c5ca4170629fdcbe6aba8e93c52b"
  pullPolicy: IfNotPresent
controller:
  type: rollout
replicaCount: 1
spot:
  enabled: true
service:
  port: 8084
  targetPort: 8084
scaleObject:
  enabled: true
configServer:
  enabled: true
discoveryServer:
  enabled: false
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-app-secrets-irsa"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: prod/petclinic
        property: openai_api_key
virtualService:
  enabled: true
vpa:
  enabled: true
analysisTemplate:
  enabled: true
destinationRule:
  enabled: true
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
