appName: db-migration

databaseMigration:
  enabled: true

image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/migrations
<<<<<<< HEAD:k8s/microservice/values/env/prod/migration-job.yaml
  tag: "6e2d22fa"
  digest: "sha256:6fcebf4b22f9b745d4430149640ea2257b70e9b65d1e3e6db036cd3a6a7edc07"
  pullPolicy: IfNotPresent

=======
  tag: "c62caca0"
  digest: "sha256:dfc4bd54fc1d0ba9949e2d066abc02ce85263acce20b89292adeab4f69e07183"
  pullPolicy: IfNotPresent
  
>>>>>>> 50dced335248a395d93e0ace9ab7a818ffafb886:k8s/microservice/values/env/main/migration-job.yaml
controller:
  type: job

replicaCount: 1

service:
  enabled: false

configServer:
  enabled: false
  
discoveryServer:
  enabled: false

serviceAccount:
  annotations:
<<<<<<< HEAD:k8s/microservice/values/env/prod/migration-job.yaml
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-app-secrets-irsa"
=======
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/prod-petclinic-cluster-appSecrets-irsa"
>>>>>>> 50dced335248a395d93e0ace9ab7a818ffafb886:k8s/microservice/values/env/main/migration-job.yaml

secretStore:
  enabled: true

externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: prod/petclinic
        property: mysql_host
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: prod/petclinic
        property: mysql_database
    - secretKey: FLYWAY_USER
      remoteRef:
        key: prod/petclinic
        property: mysql_user
    - secretKey: FLYWAY_PASSWORD
      remoteRef:
        key: prod/petclinic
        property: mysql_password

  env:
    plain:
      FLYWAY_URL: "jdbc:mysql://$(MYSQL_HOST):3306/$(MYSQL_DATABASE)"
