appName: visits-service
containerPort: 8082
springProfile: docker,mysql
image:
  registry: 509194952955.dkr.ecr.us-east-2.amazonaws.com
  repository: petclinic/visits-service
  tag: "255d2a65"
  digest: "sha256:0f691e8ac71fe2018c65a1866d4b7e44ec9dc5331090b9c292e735e0c5100c12"
  pullPolicy: IfNotPresent
controller:
  type: rollout
replicaCount: 1
spot:
  enabled: true
service:
  port: 8082
  targetPort: 8082
hpa:
  enabled: true
configServer:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-app-secrets-irsa"
secretStore:
  enabled: true
externalSecret:
  enabled: true
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: prod/petclinic
        property: mysql_host
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: prod/petclinic
        property: mysql_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: prod/petclinic
        property: mysql_user
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: prod/petclinic
        property: mysql_database
virtualService:
  enabled: true
vpa:
  enabled: true
analysisTemplate:
  enabled: true
destinationRule:
  enabled: true
volumesConfig:
  enabled: true
  volumeMounts:
    - name: tomcat-tmp
      mountPath: /tmp
  volumes:
    - name: tomcat-tmp
      emptyDir: {}
