{{- $namespaces := join "|" .Values.monitoring.managedNamespaces -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-kubernetes
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Values.monitoring.releaseLabel }}
spec:
  groups:
    - name: kubernetes.workloads.pods
      interval: 30s
      rules:
        - alert: PodCrashLooping
          expr: |
            increase(kube_pod_container_status_restarts_total{namespace=~"{{ $namespaces }}"}[15m]) > 5
          for: 0m
          labels:
            severity: critical

    - name: kubernetes.workloads.rollouts
      interval: 30s
      rules:
        - alert: ArgoRolloutDegraded
          expr: |
            rollout_phase{namespace=~"{{ $namespaces }}",phase="Degraded"} == 1
          for: 2m
          labels:
            severity: critical