admin-server:
    - services/admin-server/**
    - services/pom.xml
api-gateway:
    - services/api-gateway/**
    - services/pom.xml
config-server:
    - services/config-server/**
    - services/pom.xml
discovery-server:
    - services/discovery-server/**
    - services/pom.xml
customers-service:
    - services/customers-service/**
    - services/pom.xml
vets-service:
    - services/vets-service/**
    - services/pom.xml
visits-service:
    - services/visits-service/**
    - services/pom.xml
genai-service:
    - services/genai-service/**
    - services/pom.xml