version: "3"

tasks:
  get-repo:
    vars:
      SERVICE: '{{.SERVICE}}'
    cmds:
      - |
        if [ -z "{{.SERVICE}}" ]; then
          echo "Error: Service name is required. Usage: task get-repo SERVICE=admin-service"
          exit 1
        fi
        echo "springboot/{{.SERVICE}}"