namespace: istio-system
name: istio-ingressgateway
selectorLabels:
  app: istio-ingressgateway
  istio: ingressgateway
annotations:
  service.beta.kubernetes.io/aws-load-balancer-type: "external"
  service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxx,subnet-xxxxx"
  service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-xxxxx"
  service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:xxxx:certificate/xxxx"
  service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
  service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
istioTargetPorts:
  http: 8080
  https: 8080