argo-cd:
  global:
    domain: argocd.lefrancis.org
  configs:
    repositories:
      petclinic-gitops:
        url: "https://github.com/silasfrancis/eks-platform-petclinic"
        name: petclinic-gitops
        type: git

serviceAccount:
  create: true
  name: ""
  annotations: 
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/prod-petclinic-cluster-argocdSecrets-irsa"

externalSecrets:
  enabled: true
  refreshInterval: 1h
  secrets:
  
    repo:
      target:
        name: argocd-repo-secret
      template:
        metadata:
          labels:
            argocd.argoproj.io/secret-type: repository
        data:
          url: "git@github.com:silasfrancis/.git"
          sshPrivateKey: "{{ .sshPrivateKey }}"
          type: git
      data:
        - secretKey: sshPrivateKey
          remoteRef:
            key: prod/argocd
            property: petclinic-github-deploy-key

    notifications:
      target:
        name: argocd-notifications-secret
      template:
        data: {}
      data:
        - secretKey: slack-token
          remoteRef:
            key: prod/argocd
            property: slack-token


argocdBootstrap:
  envName: main

  defaults:
    repoURL: 
    targetRevision: main
    destination:
      server: https://kubernetes.default.svc
