apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: config-server-netpol
  namespace: petclinic
spec:
  podSelector:
    matchLabels:
      app: config-server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: 8888
