apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: visits-service-netpol
  namespace: petclinic
spec:
  podSelector:
    matchLabels:
      app: visits-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - port: 8082
    - from:
        - podSelector:
            matchLabels:
              app: admin-server
      ports:
        - port: 8082
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: config-server
      ports:
        - port: 8888
    - to:
        - podSelector:
            matchLabels:
              app: discovery-server
      ports:
        - port: 8761
    - to:
        - ipBlock:
            cidr: <your-rds-endpoint-ip>/32
      ports:
        - port: 3306