server:
  port: 9090
---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761}/eureka/
