rds:
  cidr: "10.0.2.15/32"       

ports:
  apiGateway: 8080
  configServer: 8888
  discoveryServer: 8761
  adminServer: 9090
  customersService: 8081
  visitsService: 8082
  vetsService: 8083
  genaiService: 8084
  rdsMysql: 3306

matchLabels:
  apiGateway: api-gateway
  configServer: config-server
  discoveryServer: discovery-server
  adminServer: admin-server
  customersService: customers-service
  visitsService: visits-service
  vetsService: vets-service
  genaiService: genai-service
  istioIngressGateway: istio-ingressgateway

namespaces:
  istioSystem: "istio-system"
  istioIngress: "istio-ingress"
  kubeSystem: "kube-system"
  app: "petclinic"
