{{- $net := .Values.clusterPolicy.network -}}
{{- range $nsName, $nsConfig := .Values.clusterPolicy.managedNamespaces }}
{{- if $nsConfig.istio }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-istio-controlplane
  namespace: {{ $nsName }}
  labels:
    {{- include "policies.netpol.labels" $ | nindent 4 }}
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $net.istioControlPlane.namespace }}
          podSelector:
            matchLabels:
              app: {{ $net.istioControlPlane.label }}
      ports:
        {{- range $net.istioControlPlane.egressPorts }}
        - port: {{ . }}
          protocol: TCP
        {{- end }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $net.istioControlPlane.namespace }}
      ports:
        {{- range $net.istioControlPlane.ingressPorts }}
        - port: {{ . }}
          protocol: TCP
        {{- end }}
{{- end }}
{{- end }}