{{- $net := .Values.clusterPolicy.network -}}
{{- range $nsName, $nsConfig := .Values.clusterPolicy.managedNamespaces }}
{{- if $nsConfig.dns }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: {{ $nsName }}
  labels:
    {{- include "policies.netpol.labels" $ | nindent 4 }}
spec:
  podSelector: {}
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $net.dns.namespace }}
          podSelector:
            matchLabels:
              k8s-app: {{ $net.dns.label }}
      ports:
        - port: {{ $net.dns.port }}
          protocol: UDP
        - port: {{ $net.dns.port }}
          protocol: TCP
{{- end }}
{{- end }}