{{- range $nsName, $nsConfig := .Values.clusterPolicy.managedNamespaces }}
{{- if $nsConfig.defaultDeny }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: {{ $nsName }}
  labels:
    {{- include "policies.netpol.labels" $ | nindent 4 }}
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
{{- end }}
{{- end }}