apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cloudflare-token-mirror
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: ["cert-manager"]

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: {{ include "platform-security.ClusterSecretStoreName" . }}
    target:
      name: cloudflare-dns-token
      creationPolicy: Owner
    data:
      - secretKey: cloudflare-api-token
        remoteRef:
          key: prod/platform-dns
          property: cloudflare-api-token