serviceAccount:
  create: true
  name: ""
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::509194952955:role/petclinic-prod-cluster-argocd-secrets-irsa"

externalSecrets:
  enabled: true
  refreshInterval: 1h
  secrets:
    repo:
      target:
        name: argocd-repo-secret
      template:
        metadata:
          labels:
            argocd.argoproj.io/secret-type: repository
        data:
          url: "git@github.com:silasfrancis/.git"
          sshPrivateKey: "{{ .sshPrivateKey }}"
          type: git
      data:
        - secretKey: sshPrivateKey
          remoteRef:
            key: prod/argocd
            property: petclinic-github-deploy-key

    notifications:
      target:
        name: argocd-notifications-secret
      template:
        data: {}
      data:
        - secretKey: slack-token
          remoteRef:
            key: prod/argocd
            property: slack-token

argocdBootstrap:
  envName: main

  defaults:
    repoURL:
    targetRevision: main
    destination:
      server: https://kubernetes.default.svc

ingress:
  enabled: true
  gateway: istio-ingress/ingress-internal-gateway
  argocd:
    host: argocd.internal.lefrancis.org
    serviceName: argocd-server
    port: 80