name: Application Security Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ dev ]

jobs:
  filter-updated-directories:
    uses: ./.github/workflows/path_filter.yaml

  sonarqube:
    needs: filter-updated-directories
    if: ${{ needs.filter-updated-directories.outputs.dir_changed != '[]' && needs.filter-updated-directories.outputs.dir_changed != '' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
          cache-dependency-path: "**/pom.xml"

      - name: Build and analyze with SonarQube
        run: |
            mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                -DskipTests \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.organization=silasfrancis \
                -Dsonar.projectKey=silasfrancis_spring_boot_micro_services \
                -Dsonar.exclusions=**/test/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  snyk_dependency_security_checks:
    needs: filter-updated-directories
    if: ${{ needs.filter-updated-directories.outputs.dir_changed != '[]' && needs.filter-updated-directories.outputs.dir_changed != '' }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        dir: ${{ fromJson(needs.filter-updated-directories.outputs.dir_changed) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
          cache-dependency-path: "**/pom.xml"

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Compile project
        run: mvn -B compile --file pom.xml

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --file=${{ matrix.dir }}/pom.xml --severity-threshold=high --policy-path=.snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}